#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
emby () {

container_reset
# VARIABLES ####################################################################
pgrole="emby"
port_inside01="8096"
port_outside01="8096"
traefik_extport="8096"

container_path /pg /pg
container_path /pg/unity /pg/unity
container_path /pg/data/$pgrole /config
container_path /etc/localtime /etc/localtime:ro

container_permissions UID 1000
container_permissions GID 1000
container_permissions GIDLIST 1000
# IMAGES EXPORT - 1ST IS DEFAULT ###############################################
cat <<- EOF > "/pg/images/$pgrole.images"
linuxserver/emby latest
linuxserver/emby beta
EOF
# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########
    - name: "/dev/dri Check"
      stat:
        path: "/dev/dri"
      register: dev_dri

    - name: 'XML Check - $pgrole'
      stat:
        path: /pg/data/$pgrole/config/system.xml
      register: xmlcheck

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
        devices: "{{ '/dev/dri:/dev/dri' if dev_dri.stat.exists == True | default(false) else omit }}"
        expose: '8096'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

}
