#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
nzbhydra2 () {

container_reset
# VARIABLES ####################################################################
pgrole="netdata"
port_inside01="5076"
port_outside01="5076"
traefik_extport="5076"

container_path /sys /host/sys:ro
container_path /proc /host/proc:ro
container_path /var/run/docker.sock /var/run/docker.sock

container_permissions PUID 1000
container_permissions PGID 1000
# IMAGES EXPORT - 1ST IS DEFAULT ###############################################
cat <<- EOF > "/pg/images/$pgrole.images"
linuxserver/nzbhydra2 latest
linuxserver/nzbhydra2 dev
EOF
# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

EOF
}
