#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
ombi () {

container_reset
# VARIABLES ####################################################################
pgrole="ombi"
image="linuxserver/ombi"
port_inside01="3579"
port_outside01="3579"
traefik_extport="3579"

container_path /pg/unity /unity
container_path /pg/data/$pgrole /config
container_path /etc/localtime /etc/localtime:ro

container_permissions PUID 1000
container_permissions PGID 1000

# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########
    - name: Check JSON exists
      stat:
        path: '/pg/data/$pgrole/appsettings.json'
      register: jsonfile

    - name: 'Download $pgrole appsettings.json config file'
      get_url:
        url: https://raw.githubusercontent.com/tidusjar/Ombi/master/src/Ombi/appsettings.json
        dest: /pg/data/$pgrole/appsettings.json
        owner: '1000'
        group: '1000'
        force: no
      ignore_errors: True
      when: jsonfile.stat.exists == False

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '$portstatus$port_outside01:$port_inside01'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

EOF
}
