#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
radarr () {

container_reset
# VARIABLES ####################################################################
pgrole="radarr"
image="linuxserver/radarr:preview"
port_inside01="7878"
port_outside01="7878"
traefik_extport="7878"

container_path /pg /pg
container_path /pg/unity /pg/unity
container_path /pg/data/$pgrole /config
container_path /etc/localtime /etc/localtime:ro

container_permissions PUID 1000
container_permissions PGID 1000

# IMAGES EXPORT - 1ST is DEFAULT ###############################################
cat <<- EOF > "/pg/apps/$pgrole.images"
linuxserver/radarr preview
linuxserver/radarr nightly
linuxserver/radarr latest
EOF
# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

EOF
}
