#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
sonarr () {

container_reset
# VARIABLES ####################################################################
pgrole="sonarr"
image="linuxserver/sonarr:preview"
port_inside01="8989"
port_outside01="8989"
traefik_extport="8989"

container_path /pg /pg
container_path /pg/unity /pg/unity
container_path /pg/data/$pgrole /config
container_path /etc/localtime /etc/localtime:ro

container_permissions UID 1000
container_permissions GID 1000
container_permissions GIDLIST 1000

# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '$portstatus$port_outside01:$port_inside01'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

EOF
}
