#!/bin/bash
#
# [Ansible Role]
#
# GitHub:     https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Maintainer: Admin9705 & Deiteq
# URL:        https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
sudo rm -r /opt/plexguide/menu/interface/version/version.sh
sudo mkdir -p /opt/plexguide/menu/interface/version/
sudo wget --force-directories -O /opt/plexguide/menu/interface/version/version.sh https://raw.githubusercontent.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server/Edge/menu/interface/version/version.sh &>/dev/null &
#[[ $(pwd) =~ plexguide ]] && cd ~

# If PlexGuide is Missing, it will redownload it
file="/opt/plexguide/menus/"
if [ ! -e "$file" ]; then
	echo ""
	echo "--------------------------------------------"
	echo "SYSTEM MESSAGE: PlexGuide is Missing"
	echo "--------------------------------------------"
	echo ""
	echo "NOTE: PlexGuide is Missing!"
	echo "Downloading the Latest Edge Edition!"
	echo ""
	read -n 1 -s -r -p "Press [ANY KEY] to Continue "
	echo ""
  rm -rf /opt/plexguide 1>/dev/null 2>&1
	sudo git clone https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server.git --branch Edge /opt/plexguide && sudo bash /opt/plexguide/script/install.sh && clear && echo "Execute PlexGuide Anytime By Typing: plexguide" && echo ""	exit 0
fi

bash /opt/plexguide/menu/interface/version/file.sh

file="/var/plexguide/exited.upgrade"
if [ ! -e "$file" ]; then
	echo ""
	echo "---------------------------------------------------"
	echo "SYSTEM MESSAGE: Success! PlexGuide Update Complete!"
	echo "---------------------------------------------------"
	echo ""
	read -n 1 -s -r -p "Press [ANY KEY] to Continue "
	bash /opt/plexguide/roles/ending/ending.sh
else
	rm -rf /var/plexguide/exited.upgrade 1>/dev/null 2>&1
	echo ""
	bash /opt/plexguide/roles/ending/ending.sh
fi
