#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: MountPoint
      shell: "cat /var/plexguide/multi.read"
      register: multilist

    - name: PG Main Menu
      pause:
        prompt: "\nCurrent Mounts:
                 \n{{multilist.stdout}}
                 \n\n---------------------------------------------
                 \nWelcome to the PG Multi-HD Builder!
                 \nNOTE: Be Careful Adding the Drive PG is on due use of combined space!
                 \n\n1. EXIT Interface
                 \n2. Add a Path
                 \n3. Remove a Path
                 \n4. Deploy UnionFS
                 \n\nType a [MENU CHOICE] & Press [ENTER]"    
      register: choice
      until: choice.user_input == "1" or
        choice.user_input == "2" or
        choice.user_input == "3" or
        choice.user_input == "4"
      retries: 99
      delay: 1

    - name: Set Choice
      set_fact:
        fchoice: "{{choice.user_input}}"

    - name: Exiting Interface
      shell: "echo break > /var/plexguide/multi.menu"
      when: fchoice == "1"

    - name: Add Path
      shell: "echo addpath > /var/plexguide/multi.menu"
      when: fchoice == "2"

    - name: Remove Path
      shell: "echo removepath > /var/plexguide/multi.menu"
      when: fchoice == "3"

    - name: Deploy UnionFS
      shell: "echo unionfs > /var/plexguide/multi.menu"
      when: fchoice == "4"
