#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_folders() {

common_header "⌛ FOLDERS - Building Key Directories"; sleep 2

echo ""

#start
common_fcreate /pg/transfer

#gcrypt
common_fcreate /pg/gc
common_fcreate /pg/gc/tv
common_fcreate /pg/gc/movies
common_fcreate /pg/gc/music
common_fcreate /pg/gc/ebooks

#gdrive
common_fcreate /pg/gd/tv
common_fcreate /pg/gd/movies
common_fcreate /pg/gd/music
common_fcreate /pg/gd/ebooks

#tcrypt
common_fcreate /pg/sc/tv
common_fcreate /pg/sc/movies
common_fcreate /pg/sc/music
common_fcreate /pg/sc/ebooks

#tdrive
common_fcreate /pg/sd/tv
common_fcreate /pg/sd/movies
common_fcreate /pg/sd/music
common_fcreate /pg/sd/ebooks

#unity
common_fcreate /pg/unity

#plexguide
common_fcreate /pg/plexguide

#misc
common_fcreate /pg/tmp
common_fcreate /pg/data # folder to hold container data
common_fcreate /pg/data/portainer
common_fcreate /pg/complete
common_fcreate /pg/incomplete
common_fcreate /pg/transfer
common_fcreate /pg/logs
common_fcreate /pg/apps
common_fcreate /pg/var/emergency
common_fcreate /pg/var/keys # utilized to store rclone keys
common_fcreate /pg/nzb
common_fcreate /pg/torrent
common_fcreate /pg/downloads
common_fcreate /pg/data/plexguide
common_fcreate /pg/var/traefik

}
