#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_image() {
# sets up the primary interface
if [[ -e /pg/images/$app.images ]]; then
temp_display=$(cat /pg/images/$app.images)
common_message "🚀 Image Selection ~ $app | 📂 App Type ~ $sapp | PGX Edition" "💬 INSTRUCTIONS

Type the [image:tag] to utilize for deployment! If not listed, you can still
type the name of any other related container as long as it exist!

$temp_display

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Quit & Exit Interface"
common_number
finaltyped=$typed
gitlab=0
if [[ $(echo $typed | grep "gitlab") != "" ]]; then
gitlab=1
common_header "🚀 GITLAB Image Detected! Cannot verify, but accepted input!"
common_confirm; fi

docker_tag_exists () {
  curl --silent -f -lSL https://index.docker.io/v1/repositories/$1/tags/$2 > /dev/null
}

  if [[ "$gitlab" == "0" ]]; then
  quick_check1=$(echo $typed | tr : " " | awk '{print $1}')
  quick_check2=$(echo $typed | tr : " " | awk '{print $2}')
    if docker_tag_exists $quick_check1 $quick_check2; then
        echo "$finaltyped" > /pg/data/$app/image.set
        common_header "🚀  PASSED: Setting [$app] image > [$finaltyped]"
        touch "/pg/data/$app/apply.settings"
        common_confirm
    else
        common_header "⛔️  WARNING: $typed - does not exist!"
        common_confirm
    fi
  else
    echo "$finaltyped" > /pg/data/$app/image.set
    common_header "🚀 PASSED: Image = [$finaltyped]"
    touch "/pg/data/$app/apply.settings"
    common_confirm
  fi

fi
apps_interface_sub && exit
}
