#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
container_oddball () {

container_oddball=$(cat /pg/tmp/container.oddball)
echo "$1:
           - $2" >> /pg/tmp/container.oddball
}
