#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###

# List programs to exempt from /pg/complete/{name} from uploading
# You want /pg/complete/tv to upload but not /pg/complete/nzbget to upload
# because the files are still processing
################################################################################
drives_deploy_exempt () {
  echo "nzbget" > "$path_exempt_programs"/exempt.list
  echo "sabnzbd" >> "$path_exempt_programs"/exempt.list
  echo "rutorrent" >> "$path_exempt_programs"/exempt.list
}
