#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_deploy_uploader() {

drives_menu_start_setup

service_path="/etc/systemd/system/uploader.service"
script_path="/pg/var/drives/uploader.sh"

# remove what's pending uploads in slots
rm -rf /pg/var/transport/*

# write out-script
if [[ -e "$service_path" ]]; then
common_header "💾  NOTICE:  Stopping/Disabling OLD Service - Uploader"; sleep 1
systemctl daemon-reload && systemctl stop uploader && systemctl disable uploader && rm -rf "$service_path"; fi

cat <<- EOF > "$script_path"
source /pg/mods/functions/.master.sh
drives_uploader
EOF

chown 1000:1000 $script_path
chmod 0755 $script_path

cat <<- EOF > "$service_path"
[Unit]
Description=Uploader Daemon
After=multi-user.target

[Service]
Type=simple
User=0
Group=0
ExecStart=/bin/bash /pg/var/drives/uploader.sh

ExecStop=/bin/bash /pg/var/drives/uploader.sh
TimeoutSec=5

[Install]
WantedBy=multi-user.target

EOF

common_header "💾  NOTICE:  Starting/Enabling NEW Service - uploader" && sleep 1
systemctl daemon-reload && systemctl enable uploader | fmt -w 79 && systemctl restart uploader

common_header "💾  ENABLED: Uploader Service" && sleep 1.5
}
