#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_share_user_account () {

temp_path="/pg/var/drives/shared/$sdselect/e.mail"
priorentry=$(cat $temp_path)

common_message "🚀 PlexGuide | $sdselect - G Account Login
💾 E-Mail Address for the Share Drive?

Prior Info Saved (If Any): $priorentry
[Z] To Cancel and Go Back
"

read -p "↘️  New Google Account Login? | Press [ENTER]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then drives_share_manage_module && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && drives_share_user_account && exit; fi

gcloud auth login --account "$typed"
gcloud info | grep Account: | cut -c 10- > $temp_path
account=$(cat $temp_path)

testcheck=$(gcloud auth list | grep "$typed")
if [[ "$testcheck" == "" ]]; then
    echo "NOT-SET" > $temp_path
    common_message "⛔️  WARNING: E-Mail Address Failed!"
    common_confirm
    drives_share_manage_module && exit
    # glogin
fi

echo $typed > $temp_path
common_message "💾  $typed - G Account Set!"
common_confirm && drives_share_manage_module && exit

}
