#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_docker() {

	rm -rf /bin/docker 
	common_header "⌛ INSTALLING: Docker"; sleep 2
	ansible-playbook /pg/mods/ymls/pg.yml --tags docker

}
