#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_docker_start() {

	common_header "⌛ INSTALLING: Docker Startup Script"; sleep 2
	ansible-playbook /pg/mods/ymls/pg.yml --tags docstart

}
