#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
file="/var/pgblitz/pg.number"
if [ -e "$file" ]; then
  check="$(cat /var/pgblitz/pg.number | head -c 1)"
  if [[ "$check" == "5" || "$check" == "6" || "$check" == "7" ]]; then

    tee <<-EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🌎  INSTALLER BLOCK: Notice
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
We detected PG Version $check is running! Per the instructions, PG 8
must be installed on a FRESH BOX! Exiting!
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF
    exit
  fi
fi

source /opt/plexguide/menu/functions/functions.sh
source /opt/plexguide/menu/functions/start.sh
source /opt/plexguide/menu/functions/install.sh

mkdir -p /opt/plexguide/roles/log
mkdir -p /var/plexguide/logs
mkdir -p /opt/appdata/plexguide

sudocheck
missingpull

if [[ ! -e "/bin/pgblitz" ]]; then
  cp /opt/plexguide/menu/alias/templates/pgblitz /bin
fi

chown 1000:1000 /bin/pgblitz &>/dev/null &
chmod 0755 /bin/pgblitz &>/dev/null &
# pg deploy contains pgdeploy at end
pginstall
