#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq - Sub7Seven
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
echo ""
echo "-----------------------------------------------------"
echo "SYSTEM MESSAGE: Please Copy Your Information"
echo "-----------------------------------------------------"
echo ""
cat /opt/appdata/plexguide/vpn.info
echo ""
echo "Config Info: Visit http://pgvpn.pgblitz.com or WIKI"
