#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "cloudcmd"
      intport: "8000"
      extport: "7999"
      image: "coderaiser/cloudcmd"

# CORE (MANDATORY) ############################################################
  - name: CronJob Role
    include_tasks: "/opt/plexguide/containers/_core.yml"

# FILE MOVES & CHECKS #########################################################
  - name: Check config file exists
    stat:
      path: "/opt/appdata/{{pgrole}}/.cloudcmd.json"
    register: cloud_json

  - name: Install config.json
    template:
      src: /opt/plexguide/containers/templates/cloudcmd.json
      dest: /opt/appdata/{{pgrole}}/.cloudcmd.json
      force: yes
    when: cloud_json.stat.exists == False

# LABELS ######################################################################

  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.enable: "true"
        traefik.port: "{{intport}}"
        traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"
        traefik.frontend.auth.forward.address: "{{gauth}}"

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - /:/SERVER
        - /opt/appdata/{{pgrole}}:/root/

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000

# MAIN DEPLOYMENT #############################################################

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "{{pgrole}}"
      image: "{{image}}"
      pull: yes
      published_ports:
        - "{{ports.stdout}}{{extport}}:{{intport}}"
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: always
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      labels: "{{pg_labels}}"
