#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "deluge"
      intport: "8112"
      extport: "8112"
      intport2: "58846"
      extport2: "58846"
      intport3: "58946"
      extport3: "58946"
      image: "linuxserver/deluge"

# CORE (MANDATORY) ############################################################
  - name: CronJob Role
    include_tasks: "/opt/plexguide/containers/_core.yml"

# LABELS ######################################################################

  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.frontend.auth.forward.address: "{{gauth}}"
        traefik.enable: "true"
        traefik.port: "{{intport}}"
  
        traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - "/opt/appdata/{{pgrole}}:/config"
        - "/mnt/unionfs:/unionfs"
        - "{{path.stdout}}/incomplete/{{pgrole}}:/incomplete"
        - "{{path.stdout}}/downloads/{{pgrole}}/:/downloads/{{pgrole}}"
        - "/etc/localtime:/etc/localtime:ro"

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000

# MAIN DEPLOYMENT #############################################################
  - name: "Copy scripts into directory - {{pgrole}}"
    copy:
      src: ./templates/deluge_extract.sh
      dest: /opt/appdata/{{pgrole}}/scripts
      directory_mode: yes
      force: yes
      owner: 1000
      group: 1000
      mode: 0755

  - name: "Create scripts folder - {{pgrole}}"
    file:
      path: /opt/appdata/{{pgrole}}/plugins
      state: directory
      owner: 1000
      group: 1000
      mode: 0755

  - name: "Copy scripts into directory - {{pgrole}}"
    copy:
      src: ./templates/deluge/plugins
      dest: /opt/appdata/{{pgrole}}
      directory_mode: yes
      force: yes
      owner: 1000
      group: 1000
      mode: 0755

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "{{pgrole}}"
      image: "{{image}}"
      pull: yes
      published_ports:
        - "{{ports.stdout}}{{extport}}:{{intport}}"
        - "{{ports.stdout}}{{extport2}}:{{intport2}}"
        - "{{ports.stdout}}{{extport3}}:{{intport3}}"
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: always
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      labels: "{{pg_labels}}"
