#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

# FACTS #######################################################################

  - name: "Set Known Facts"
    set_fact:
      pgrole: "ombihdr"
      intport: "3579"
      extport: "3577"
      image: "linuxserver/ombi"

# CORE (MANDATORY) ############################################################
  - name: CronJob Role
    include_tasks: "/opt/plexguide/containers/_core.yml"

# PRETASKS ####################################################################
  - name: Check JSON exists
    stat:
      path: "/opt/appdata/{{pgrole}}/appsettings.json"
    register: jsonfile

  - name: "Download {{pgrole}} appsettings.json config file"
    get_url:
      url: https://raw.githubusercontent.com/tidusjar/Ombi/master/src/Ombi/appsettings.json
      dest: /opt/appdata/{{pgrole}}/appsettings.json
      owner: 1000
      group: 1000
      force: no
    ignore_errors: True
    when: jsonfile.stat.exists == False

# LABELS ######################################################################
  - name: "Setting PG Labels"
    set_fact:
      pg_labels:
        traefik.enable: "true"
        traefik.port: "{{intport}}"
        traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"
        traefik.frontend.auth.forward.address: "{{gauth}}"

  - name: "Setting PG Volumes"
    set_fact:
      pg_volumes:
        - "/opt/appdata/{{pgrole}}:/config"
        - "/etc/localtime:/etc/localtime:ro"
        - "/opt/appdata/{{pgrole}}/appsettings.json:/opt/{{pgrole}}/appsettings.json"

  - name: "Setting PG ENV"
    set_fact:
      pg_env:
        PUID: 1000
        PGID: 1000

# MAIN DEPLOYMENT #############################################################

  - name: "Deploying Container - {{pgrole}}"
    docker_container:
      name: "{{pgrole}}"
      image: "{{image}}"
      pull: yes
      published_ports:
        - "{{ports.stdout}}{{extport}}:{{intport}}"
      volumes: "{{pg_volumes}}"
      env: "{{pg_env}}"
      restart_policy: always
      networks:
        - name: plexguide
          aliases:
            - "{{pgrole}}"
      state: started
      labels: "{{pg_labels}}"
