#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: "Set Known Facts"
      set_fact:
        pgrole: "qbittorrent"
        intport: "8080"
        extport: "8080"
        image: "linuxserver/qbittorrent"

    # CORE (MANDATORY) #############################################################
    - name: "Including cron job"
      include_tasks: "/opt/plexguide/containers/_core.yml"

    # EXTRA FOR QBITORRENT #########################################################
    - name: Create Basic directories for qBittorrent
      file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
      with_items:
        - "{{path.stdout}}/{{pgrole}}"
        - "/opt/appdata/{{pgrole}}"
        - "/opt/appdata/{{pgrole}}/config"

    # LABELS ######################################################################

    - name: "Adding Traefik"
      set_fact:
        pg_labels:
          traefik.frontend.auth.basic.users: "{{auth.stdout}}"
          traefik.enable: "true"
          traefik.port: "{{intport}}"
          traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}},{{tldset}}"

    - name: "Setting PG Volumes"
      set_fact:
        pg_volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/opt/appdata/{{pgrole}}:/config"
          - "{{path.stdout}}/incomplete/{{pgrole}}:/incomplete"
          - "{{path.stdout}}/downloads/{{pgrole}}:/downloads/{{pgrole}}"

    - name: "Setting PG ENV"
      set_fact:
        pg_env:
          PUID: 1000
          PGID: 1000

    # MAIN DEPLOYMENT #############################################################
    - name: ConfCheck
      stat:
        path: "/opt/appdata/{{pgrole}}/config/qBittorrent/qBittorrent.conf"
      register: confcheck

    - name: "Deploying {{pgrole}}"
      docker_container:
        name: "{{pgrole}}"
        image: "{{image}}"
        pull: yes
        published_ports:
          - "{{ports.stdout}}{{extport}}:{{intport}}"
        volumes: "{{pg_volumes}}"
        env: "{{pg_env}}"
        restart_policy: always
        networks:
          - name: plexguide
            aliases:
              - "{{pgrole}}"
        state: started
        labels: "{{pg_labels}}"

    # ENDING TASK FOR RUTORRENT ####################################################
    - name: "Configuring {{pgrole}} for first time use"
      block:
        - name: "Wating for {{pgrole}} to start"
          wait_for:
            path: "/opt/appdata/{{pgrole}}/config/qBittorrent/qBittorrent.conf"
            state: present

        - name: "Wait 5 Seconds"
          wait_for:
            timeout: 5

        - name: Set Download Location
          lineinfile:
            path: "/opt/appdata/{{pgrole}}/config/qBittorrent/qBittorrent.conf"
            regexp: "Downloads.SavePath="
            line: "Downloads.SavePath=/downloads/{{pgrole}}"
            state: present

        - name: Set Incomplete Download Location
          lineinfile:
            path: "/opt/appdata/{{pgrole}}/config/qBittorrent/qBittorrent.conf"
            regexp: "Downloads.TempPath="
            line: "Downloads.TempPath=/incomplete"
            state: present

        - name: Turn off DHT
          lineinfile:
            path: "/opt/appdata/{{pgrole}}/config/qBittorrent/qBittorrent.conf"
            regexp: "Bitorrent.DHT="
            line: "Bitorrent.DHT=false"
            state: present

        - name: Restart Container
          docker_container:
            name: qbittorrent
            state: started

      when: not confcheck.stat.exists
