#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
clear
rm -rf /pg
wget -nc https://raw.githubusercontent.com/plexguide/PlexGuide.com/mods/install/main.sh -O- | bash
