## Notes: https://wiki.archlinux.org/index.php/CPU_frequency_scaling
#!/bin/bash
#
# [Cloudbox Ansible Role]
#
# Author:   13uddz & Desmonic
# URL:      https://cloudbox.rocks
#
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
# Further Enhancements & Options By: PlexGuide.com
# GitHub: https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
#################################################################################
---
- name: Check service exists
  stat:
    path: "/etc/systemd/system/scan.service"
  register: scan_service

- name: Stop existing scan service
  systemd: state=stopped name=scan
  when: scan_service.stat.exists

- name: Create scan directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
  with_items:
    - /opt/appdata/scan

- name: Clone scan
  git:
    repo: https://github.com/Admin9705/scan
    dest: /opt/appdata/scan
    version: master
    force: yes
    
- name: Install pip requirements
  pip:
    requirements: /opt/appdata/scan/requirements.txt
    executable: pip2

- name: Check config exists
  stat:
    path: "/opt/appdata/scan/config/config.json"
  register: scan_config

- name: "Generate 32 character SERVER_PASS"
  shell: "pwgen 32 1"
  register: scan_pass
  when: scan_config.stat.exists == False

- name: Import default config
  template:
    src: config.json.js2
    dest: /opt/appdata/scan/config/config.json
    force: yes
  when: scan_config.stat.exists == False

- name: Set scan.py as executable
  file:
    path: /opt/appdata/scan/scan.py
    mode: a+x

- name: Set directory permissions
  file: "path=/opt/appdata/scan state=directory owner=1000 group=1000 recurse=yes"

- name: Import scan service
  template:
    src: scan.service.js2
    dest: /etc/systemd/system/scan.service 
    force: yes
  when: scan_service.stat.exists == False

- name: Start scan service
  systemd: state=started name=scan daemon_reload=yes enabled=yes