#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'lazylibrarian'
        intport: '5299'
        extport: '5299'
        image: 'linuxserver/lazylibrarian'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    - name: 'Checking for existing app data'
      stat:
        path: /pg/data/{{pgrole}}/config.ini
      register: inicheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/pg/data/{{pgrole}}:/config'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/etc/localtime:/etc/localtime:ro'
          - '/mnt:/mnt'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION ####################################################

    - name: 'Waiting for {{pgrole}} to initialize'
      wait_for:
        path: '/pg/data/{{pgrole}}/config.ini'
        state: present
        delay: 5

    - name: 'Stopping {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        state: stopped

    - name: Set eBooks library Location
      ini_file:
        path: '/pg/data/{{pgrole}}/config.ini'
        section: General
        option: ebook_dir
        value: '{{path.stdout}}/unionfs/ebooks'
        state: present

    - name: Set Audio Books library Location
      ini_file:
        path: '/pg/data/{{pgrole}}/config.ini'
        section: General
        option: audio_dir
        value: '{{path.stdout}}/unionfs/abooks'
        state: present

    - name: Set downloads location
      ini_file:
        path: '/pg/data/{{pgrole}}/config.ini'
        section: General
        option: download_dir
        value: '{{path.stdout}}/downloads/sabnzbd/ebooks,{{path.stdout}}/downloads/nzbget/ebooks,{{path.stdout}}/downloads/rutorrent/ebooks,{{path.stdout}}/downloads/qbittorrent/ebooks'
        state: present

    # FIRST TIME CONFIGURATION ####################################################

    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: Enable audio tab
          ini_file:
            path: '/pg/data/{{pgrole}}/config.ini'
            section: General
            option: audio_tab
            value: 1
            state: present

        - name: Enable series tab
          ini_file:
            path: '/pg/data/{{pgrole}}/config.ini'
            section: General
            option: series_tab
            value: 1
            state: present

        - name: 'Configuring downloaders'
          block:
            - name: Set deluge host
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: DELUGE
                option: deluge_host
                value: deluge
                state: present

            - name: Set deluge label
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: DELUGE
                option: deluge_label
                value: ebooks
                state: present

            - name: Set deluge port
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: DELUGE
                option: deluge_port
                value: 8112
                state: present

            - name: Set nzbget host
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: NZBGet
                option: nzbget_host
                value: http://nzbget
                state: present

            - name: Set nzbget port
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: NZBGet
                option: nzbget_port
                value: 6789
                state: present

            - name: Set nzbget label
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: NZBGet
                option: nzbget_label
                value: ebooks
                state: present

            - name: Set qbittorrent host
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: QBITTORRENT
                option: qbittorrent_host
                value: qbittorrent
                state: present

            - name: Set qbittorrent port
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: QBITTORRENT
                option: qbittorrent_port
                value: 8080
                state: present

            - name: Set qbittorrent label
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: QBITTORRENT
                option: qbittorrent_label
                value: ebooks
                state: present

            - name: Set sabnzbd host
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: SABnzbd
                option: sab_host
                value: sabnzbd
                state: present

            - name: Set sabnzbd label
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: SABnzbd
                option: sab_label
                value: ebooks
                state: present

            - name: Set rtorrent host
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: RTORRENT
                option: rtorrent_host
                value: rutorrent
                state: present

            - name: Set rtorrent label
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: RTORRENT
                option: rtorrent_label
                value: ebooks
                state: present

        - name: 'Configuring indexers'
          block:
            - name: Setup hydra on Newznab0 host
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: Newznab0
                option: host
                value: nzbhydra:5076
                state: present

            - name: Setup hydra on Torznab0 host
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: Torznab0
                option: host
                value: nzbhydra:5076/torznab
                state: present

            - name: Setup hydra on Torznab0 priority
              ini_file:
                path: '/pg/data/{{pgrole}}/config.ini'
                section: Torznab0
                option: dlpriority
                value: 1
                state: present

      when: not inicheck.stat.exists

    - name: Restart {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: started
