#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ombi'
        intport: '3579'
        extport: '3579'
        image: 'linuxserver/ombi'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/coreapps/apps/_core.yml'

    # PRETASKS ####################################################################
    - name: Check JSON exists
      stat:
        path: '/pg/data/{{pgrole}}/appsettings.json'
      register: jsonfile

    - name: 'Download {{pgrole}} appsettings.json config file'
      get_url:
        url: https://raw.githubusercontent.com/tidusjar/Ombi/master/src/Ombi/appsettings.json
        dest: /pg/data/{{pgrole}}/appsettings.json
        owner: '1000'
        group: '1000'
        force: no
      ignore_errors: True
      when: jsonfile.stat.exists == False

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/pg/data/{{pgrole}}:/config'
          - '/etc/localtime:/etc/localtime:ro'
          - '/pg/data/{{pgrole}}/appsettings.json:/opt/{{pgrole}}/appsettings.json'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '1000'
          PGID: '1000'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'
