#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_ports() {

port_display=$(cat "/pg/data/$app/port.setting")
if [[ "$port_display" == "OPEN" ]]; then echo "CLOSED" > "/pg/data/$app/port.setting"
else echo "OPEN" > "/pg/data/$app/port.setting"; fi

touch "/pg/data/$app/apply.settings"
}
