#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_menu() {

personal_blank () {
  if [[ $(ls /pg/mods/containers/personal) == "" ]]; then
  common_header "⛔️ WARNING! No Personnal Apps Detected! - plexguide.com/wiki/no-apps"
  common_confirm
  apps_menu && exit; fi
}

apps_interface_start

common_message "🚀  PG Applications Interface" "💬 More Info? Visit ~ http://apps.plexguide.com

[1] Primary
[2] Community
[3] Personal
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[D] Default Settings
[S] Shield Setup
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface"
common_number

rm -rf /pg/tmp/appstoinstall.list && touch /pg/tmp/appstoinstall.list
touch /pg/tmp/list.tmp
case $typed in
    1 ) sapp="primary" && ls -p /pg/mods/containers/$sapp/ | grep -v / > "/pg/tmp/list.tmp" && apps_interface ;;
    2 ) sapp="community" && ls -p /pg/mods/containers/$sapp/ | grep -v / > "/pg/tmp/list.tmp" && apps_interface ;;
    3 ) personal_blank && sapp="personal" && ls -p /pg/mods/containers/$sapp/ | grep -v / > "/pg/tmp/list.tmp" && apps_interface ;;
    d ) apps_default_interface ;;
    D ) apps_default_interface ;;
    s ) shield_setup ;;
    S ) shield_setup ;;
    z ) start_menu ;;
    Z ) start_menu ;;
    * ) apps_menu ;;
esac

}
