#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_interface_start() {

common_fcreate_silent /pg/var/defaults
common_fcreate_silent /pg/data/$app
common_fcreate_silent /pg/var/repos

common_fcreate_silent /pg/mods/containers/personal
common_fcreate_silent /pg/mods/containers/primary
common_fcreate_silent /pg/mods/containers/community

common_main /pg/var/defaults/default.port OPEN default_port
common_main /pg/var/defaults/default.shield ON default_shield
common_main /pg/data/plex/plex.claim "" plex_token_status

common_main /pg/var/repos/repo.personal1 plexguide/personal personal1
common_main /pg/var/repos/repo.personal2 v1 personal2

common_main /pg/var/repos/repo.community1 plexguide/community community1
common_main /pg/var/repos/repo.community2 v1 community2

common_main /pg/var/repos/repo.primary1 plexguide/primary primary1
common_main /pg/var/repos/repo.primary2 v1 primary2

common_main /pg/var/defaults/user.check Daily user_check
}
