#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_interface_sub() {

app_status=$(docker ps | grep "\<$app\>")

if [[ "$app_status" == "" ]]; then a1="Not Installed"; else a1="Re-Install"; fi
if [[ "$app_status" == "" ]]; then u1=""; else u1="
[U] UnInstall"; fi

if [[ "$app_status" != "Not Installed" && -e "/pg/data/$app/apply.settings" ]]; then app_warning="
WARNING: ReInstall to Apply Recent Changes"; fi

port_display=$(cat /pg/data/$app/port.setting)
shield_display=$(cat /pg/data/$app/shield.setting)

# sets up the primary interface
common_message "🚀 App Interface ~ $app | 📂 App Type ~ $sapp | PGX Edition" "💬  Visit ~ https://plexguide.com/wiki/$app

[A] Application   | ${a1}
[B] Backups       | Not Ready
[P] Ports         | [$port_display] - Not Ready
[S] Shield        | [$shield_display] - Not Ready
[T] Traefik CNAME | Not Ready${u1}
$app_warning
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Quit & Exit Interface $installinfo"
common_number

echo "apps_install() {" > /pg/mods/functions/apps_install
echo "$app" >> /pg/mods/functions/apps_install
echo "}" >> /pg/mods/functions/apps_install

case $typed in
    A ) apps_install ;;
    a ) apps_install ;;
    u ) apps_uninstall ;;
    U ) apps_uninstall ;;
    p ) apps_ports ;;
    P ) apps_ports ;;
    z ) apps_menu ;;
    Z ) apps_menu ;;
    * ) apps_interface_sub ;;
esac

apps_interface_sub
}
