#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_ports() {

port_display=$(cat "/pg/data/$app/port.setting")
if [[ "$port_display" == "OPEN" ]]; then
  echo "CLOSED" > "/pg/data/$app/port.setting"
  echo "127.0.0.1:" > "/pg/data/$app/port.info"
else
  echo "OPEN" > "/pg/data/$app/port.setting"
  echo "" > "/pg/data/$app/port.info"
fi

touch "/pg/data/$app/apply.settings"
}
