#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_interface_sub() {

app_status=$(docker ps | grep "\<$app\>")

if [[ "$app_status" == "" ]]; then a1="Not Installed"; else a1="Re-Install"; fi
if [[ "$app_status" == "" ]]; then u1=""; else u1="
[U] UnInstall"; fi

if [[ "$a1" != "Not Installed" && -e "/pg/data/$app/apply.settings" ]]; then app_warning="
⛔️  WARNING: Re-Install to Apply Recent Changes"; else app_warning=""; fi

port_display=$(cat /pg/data/$app/port.setting)
shield_display=$(cat /pg/data/$app/shield.setting)

traefik_check=$(docker ps | grep "traefik")
if [[ ! -e "/pg/data/$app/cname.traefik" ]]; then echo $app > "/pg/data/$app/cname.traefik"; fi
if [[ "$traefik_check" == "" ]]; then traefik_display=""; else
common_main /pg/data/$pgrole/cname.traefik "$app" cname
traefik_display="
[T] Traefik CNAME  [$cname]"; fi

shield_check=$(docker ps | grep "shield")
if [[ "$shield_check" == "" ]]; then shield_display2=""; else shield_display2="
[S] Shield         [$shield_display]"; fi

if [[ ! -e "/pg/data/$app/image.set" ]]; then
  cat "/pg/images/$app.images" | head -n +1 > "/pg/data/$app/image.temp"
  cat "/pg/data/$app/image.temp" | awk '{print $1 ":"$2'} > "/pg/data/$app/image.set"
  images_display=$(cat "/pg/data/$app/image.set")
else images_display=$(cat "/pg/data/$app/image.set"); fi

# sets up the primary interface
common_message "🚀 App Interface ~ $app | 📂 App Type ~ $sapp | PGX Edition" "💬  Visit ~ https://plexguide.com/wiki/$app

[A] Application    [${a1}]
[B] Backups        [Not Ready]
[I] Image          [$images_display]
[P] Ports          [$port_display]${shield_display2}${traefik_display}${u1}
$app_warning
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Quit & Exit Interface $installinfo"
common_number

echo "apps_install() {" > /pg/mods/functions/apps_install
echo "$app" >> /pg/mods/functions/apps_install
echo "}" >> /pg/mods/functions/apps_install

case $typed in
    A ) apps_install && apps_interface_sub && exit ;;
    a ) apps_install && apps_interface_sub && exit ;;
    u ) apps_uninstall && apps_interface_sub && exit ;;
    U ) apps_uninstall && apps_interface_sub && exit ;;
    i ) apps_image && apps_interface_sub && exit ;;
    I ) apps_image && apps_interface_sub && exit ;;
    p ) apps_ports && apps_interface_sub && exit ;;
    P ) apps_ports && apps_interface_sub && exit ;;
    s ) apps_shield && apps_interface_sub && exit ;;
    S ) apps_shield && apps_interface_sub && exit ;;
    t ) apps_cname && apps_interface_sub && exit ;;
    T ) apps_cname && apps_interface_sub && exit ;;
    z ) apps_menu && apps_interface_sub && exit ;;
    Z ) apps_menu && apps_interface_sub && exit ;;
    * ) apps_interface_sub && exit ;;
esac

}
