#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_interface_sub() {

app_status=$(docker ps | grep "\<$app\>")

if [[ "$app_status" == "" ]]; then a1="Not Installed"; else a1="Re-Install"; fi
if [[ "$app_status" == "" ]]; then u1=""; else u1="
[U] UnInstall"; fi

if [[ "$a1" != "Not Installed" && -e "/pg/data/$app/apply.settings" ]]; then app_warning="
⛔️  WARNING: Re-Install to Apply Recent Changes"; else app_warning=""; fi

port_display=$(cat /pg/data/$app/port.setting)
shield_display=$(cat /pg/data/$app/shield.setting)

if [[ ! -e "/pg/data/$app/cname.traefik" ]]; then echo $app > /pg/data/$app/cname.traefik; fi
common_main /pg/data/$app/cname.traefik $app cname
traefik_check=$(docker ps | grep "traefik")
if [[ "$traefik_check" == "" ]]; then traefik_display=""; else traefik_display="
[T] Traefik CNAME  [$cname]"; fi

shield_check=$(docker ps | grep "shield")
if [[ "$shield_check" == "" ]]; then shield_display2=""; else shield_display2="
[S] Shield         [$shield_display]"; fi

if [[ -e "/pg/images/$app.images" ]]; then
  if [[ ! -e "/pg/data/$app/image.set" ]]; then
  cat "/pg/images/$app.images" | head -n +1 > "/pg/data/$app/image.temp"; fi
  cat "/pg/data/$app/image.temp" | awk '{print $1 ":"$2'} > "/pg/data/$app/image.set"
  images_display=$(cat /pg/data/$app/image.set)
else images_display="N/A"; fi

# sets up the primary interface
common_message "🚀 App Interface ~ $app | 📂 App Type ~ $sapp | PGX Edition" "💬  Visit ~ https://plexguide.com/wiki/$app

[A] Application    [${a1}]
[B] Backups        [Not Ready]
[I] Image          [$images_display]
[P] Ports          [$port_display]${shield_display2}${traefik_display}${u1}
$app_warning
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Quit & Exit Interface $installinfo"
common_number

echo "apps_install() {" > /pg/mods/functions/apps_install
echo "$app" >> /pg/mods/functions/apps_install
echo "}" >> /pg/mods/functions/apps_install

case $typed in
    A ) apps_install ;;
    a ) apps_install ;;
    u ) apps_uninstall ;;
    U ) apps_uninstall ;;
    p ) apps_ports ;;
    P ) apps_ports ;;
    s ) apps_shield ;;
    S ) apps_shield ;;
    t ) apps_cname ;;
    T ) apps_cname ;;
    z ) apps_menu ;;
    Z ) apps_menu ;;
    * ) apps_interface_sub ;;
esac

apps_interface_sub && exit
}
