#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_interface() {

installqueuecheck=$(cat /pg/tmp/appstoinstall.list)
if [ ! -z "$installqueuecheck" ]; then installinfo="| [A] To Install Apps(s)"; else installinfo=""; fi

echo
fmt -w 79 "/pg/tmp/list.tmp" > "/pg/tmp/wrap.list"
app_display=$(cat /pg/tmp/list.wrap)
fmt -w 79 "/pg/tmp/appstoinstall.list" > "/pg/tmp/appstoinstall.wrap"
apps_to_install=$(cat /pg/tmp/appstoinstall.wrap)

common_message "🚀 Multi-App Installer | PGX Edition | 📂 App Install ~ $app_select" "
$app_display

💾 Apps Queued for Installation

$apps_to_install

[Z] Quit & Exit Interface $installinfo"

read -p '↘️  Type App to Install | Press [ENTER]: ' typed < /dev/tty
  if [[ "$typed" == "z" || "$typed" == "Z" ]]; then apps_menu; exit; fi
  if [[ "$typed" == "A" || "$typed" == "a" ]]; then apps_loop_install; exit; fi

existcheck=$(echo $app_display | grep "$typed" -w)
  if [ -z "$existcheck" ]; then echo "";
  read -p '⛔️  '$typed' <<< does not exist or has been selected | Press [ENTER]' badinput < /dev/tty
  apps_interface; fi

dockerlist=$(docker container ls --format 'table {{.Names}}' | tail -n +2)
  if [[ "1" = $(echo $dockerlist | grep -c "\<$typed\>") ]]; then tempinput="null";
    while [[ "$tempinput" && "Y" && "$tempinput" != "y" && "$tempinut" != "N" && "$tempinput" != "n" ]]; do
    read -p '⛔️  '$typed' is already installed! Reinstall ~ Y or N? ' tempinput < /dev/tty; done; fi
  if [[ "$tempinput" == "n" || "tempinput" == "N" ]]; then apps_interface; fi

echo "$typed" >> /pg/tmp/appstoinstall.list
sed -i -e "/$typed/d" "/pg/tmp/list.tmp"

## recycle menu back to user
apps_interface

}
