#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_uninstall() {

common_header "WARNING! Uninstalling the app removes the data also!"
echo ""
read -p "↘️  Type [Y] Uninstall or [Z] Exit | Press [Enter]: " typed < /dev/tty

if [[ "$typed" == "y" || "$typed" == "Y" ]]; then
  echo ""
  docker stop $app
  docker rm $app
  echo ""
read -p "↘️  Uninstalled - $app | Press [Enter]" typed < /dev/tty
elif [[ "$typed" == "z" || "$typed" == "Z" || "$typed" == "n" || "$typed" == "N" ]]; then
  apps_interface_sub
else
  common_header "INVALID Selection! Please try again!"
  echo
  common_confirm
apps_interface_sub; fi
}
