#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_uninstall() {

common_header "WARNING! Uninstalling the app removes the data also!"
read -p "↘️  Type App Name to Uninstall - $app | Press [ENTER]" typed < /dev/tty

docker stop $app
docker rm $app

echo ""
read -p "↘️  Uninstalled $app | Press [ENTER]" typed < /dev/tty
}
