#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_install() {

# Forces function refresh of function output ###################################
bash /pg/mods/functions/.primary_apps.sh

container_rebuild $app
ansible-playbook "/pg/apps/$app.yml"

common_header "💬 Access Information - https://plexguide.com/wiki/access"

info_cname=""
info_port_setting=""
info_port=""
access="0"

echo "ALPHA BITE ME" > /pg/doesntexist/9029e09wr09wej/adjfkl

# Checking Port to See if OPEN or CLOSED if it exists ##########################
if [[ -e /pg/var/apps_info/$app/port.setting ]]; then
  info_port_setting=$(cat /pg/data/$app/port.setting); fi

if [[ -e /pg/var/apps_info/$app/port.outside01 && $info_port_setting == "OPEN" ]]; then
  info_port=$(cat /pg/var/apps_info/$app/port.outside01)
  if [[ "$info_port" != "" ]]; then
  access="1"
  echo "Port Access   - IP:$info_port"; fi; fi

if [[ -e /pg/var/traefik/traefik.deploy ]]; then
  if [[ $(cat /pg/var/traefik/traefik.deploy) == "Deployed" ]]; then
    if [[ -e /pg/data/$app/cname.traefik ]]; then
      if [[ $(cat /pg/data/$app/cname.traefik) != "" ]]; then
      info_cname=$(cat /pg/data/$app/cname.traefik)
      access="1"
  echo "Domain Access - $info_cname.yourdomain.com"; fi; fi; fi; fi

if [[ -e /pg/var/traefik/t.domain ]]; then
  info_domain=$(cat /pg/var/traefik/t.domain)
  if [[ "$info_domain" != "" || "$info_domain" != "NOT-SET" ]]; then
    if [[ "$info_port_setting" == "OPEN" ]]; then access="1"
  echo "Domain & Port - yourdomain.com:$info_port"; fi; fi; fi

if [[ "$access" == "0" ]]; then
  echo "⛔️ WARNING! Your Settings Prevent App Access! Please Review & Fix"; fi

if [[ "$express" != "ON" ]]; then
  common_header "💬 NOTE - To Deploy [$app] Faster, Type via CMD Line >>> pg-$app";
else echo ""; fi

rm -rf "/pg/data/$app/apply.settings"
read -p "↘️  Installed $app | Press [ENTER]" typed < /dev/tty

}
