#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_default_interface() {

common_main /pg/var/defaults/default.port OFF default_port
common_main /pg/var/defaults/default.shield ON default_shield

# sets up the primary interface
common_message "🚀 App Interface ~ $app | 📂 App Type ~ $sapp | PGX Edition" "Default settings prevent user from setting up a different setting via every
new app installation.

[P] Ports  [$default_port]
[S] Shield [$default_shield]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Quit & Exit Interface $installinfo"
common_number

default_ports() {
if [[ "$default_port" == "ON" ]]; then
echo "OFF" > /pg/var/defaults/default.port
else echo "ON" > /pg/var/defaults/default.port; fi
}

default_shield() {
if [[ "$default_shield" == "ON" ]]; then
echo "OFF" > /pg/var/defaults/default.shield
else echo "ON" > /pg/var/defaults/default.shield; fi
}

case $typed in
    p ) default_ports && apps_default_interface ;;
    P ) default_ports && apps_default_interface ;;
    s ) default_shield && apps_default_interface ;;
    S ) default_shield && apps_default_interface ;;
    z ) apps_menu ;;
    Z ) apps_menu ;;
    * ) apps_default_interface ;;
esac

}
