#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_cname() {

common_main /pg/data/$app/cname.traefik $app cname

apps_cname_change_confirm () {
  common_header "Correct? [y|n]? $cname_set"
  common_number
  case $typed in
      y ) a=a ;;
      Y ) a=a ;;
      n ) apps_cname_change && exit ;;
      N ) apps_cname_change && exit ;;
      * ) apps_cname_change_confirm && exit ;;
  esac

  echo "$cname_set" > /pg/data/$app/cname.traefik

  common_header "CNAME [$cname_set] set for [$app]"
  common_confirm
  app_status=$(docker ps | grep "\<$app\>")
  if [[ "$app_status" == "" ]]; then a1="Not Installed"; else a1="Re-Install"; fi
  if [[ "$a1" != "Not Installed" && -e "/pg/data/$app/apply.settings" ]]; then app_warning="
  ⛔️  WARNING: Re-Install to Apply Recent Changes"; else app_warning=""; fi
  apps_interface_sub && exit
}

apps_cname_change () {
  common_header "What is the New Subdomain >>> $app? Type [Z] to Exit!"
  common_number
  if [[ "$typed" == "z" || "$typed" == "Z" ]]; then apps_interface_sub && exit; fi
  if [[ "$typed" == "" ]]; then common_header "⛔️  WARNING: Cannot Be Blank" && common_confirm && apps_cname_change && exit; fi

  typed=$(echo $typed | awk '{print $1}')
  cname_set=$(echo "$typed" | awk '{print tolower($0)}')

  apps_cname_change_confirm
}

apps_cname_change && exit
}
