#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_gen_lists() {

wrap_path="/pg/tmp/list.wrap"

ls -p /pg/mods/containers/$app_select/ | grep -v / > "/pg/tmp/list.tmp"
fmt -w 79 "/pg/tmp/list.tmp" > "$wrap_path"

#sed -i -e "/pgui/d" "$wrap_path"


}
