#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_menu() {

apps_interface_start

personal_blank () {
  if [[ $(ls /pg/mods/containers/personal) == "" ]]; then
  common_header "⛔️ WARNING! No Personnal Apps Detected! - plexguide.com/wiki/no-apps"
  common_confirm
  apps_menu && exit; fi
}

pull_check () {
pull_check=$(date +%s)
common_main /pg/var/defaults/pull.check "$pull_check" stored_check
common_main /pg/var/defaults/user.check Daily user_check
timediff=$(($pull_check-$stored_check))

to_pull="NULL"
if [[ "$user_check" == "Daily" ]]; then
  if [[ "$timediff" -gt 86400 ]]; then to_pull="ON"; else to_pull="OFF"; fi
elif [[ "$user_check" == "Weekly" ]]; then
  if [[ "$timediff" -gt 604800 ]]; then to_pull="ON"; else to_pull="OFF"; fi
elif [[ "$user_check" == "Hourly" ]]; then
  if [[ "$timediff" -gt 3600 ]]; then to_pull="ON"; else to_pull="OFF"; fi
elif [[ "$user_check" == "Immediate" ]]; then to_pull=ON
elif [[ "$user_check" == "Off" ]]; then to_pull="OFF"; fi
}

pull_actions () {
if [[ "$to_pull" == "ON" ]]; then

if [[ "$sapp" == "" ]]; then echo BAD PULL - CANCEL; apps_interface_start && exit; fi
repo1=$(cat /pg/var/repos/repo.${sapp}1)
repo2=$(cat /pg/var/repos/repo.${sapp}2)
common_header "💬 Pulling Repo - $sapp"
rm -rf /pg/var/$sapp
git clone -b ${repo2} --single-branch https://github.com/${repo1}.git /pg/var/$sapp
common_fcreate_silent /pg/var/$sapp
bash /pg/mods/functions/.create.sh 1>/dev/null 2>&1
bash /pg/mods/functions/.$sapp_apps.sh 1>/dev/null 2>&1
cp -f /pg/var/$sapp/* /pg/mods/containers/$sapp/ 1>/dev/null 2>&1
echo $(date +%s) > /pg/var/defaults/pull.check
fi
}

echo "TIME DIFF $timediff | to Pull $to_pull"
pull_check
common_message "🚀  PG Applications Interface" "💬 More Info? Visit ~ plexguide.com/wiki/apps | PULL: $to_pull

[1] Primary
[2] Community
[3] Personal
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--- Settings -----------------------------------------------------------------
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[4] Repos
[5] Shield
[6] Default
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface"

common_number

common_fcreate_silent /pg/mods/containers/personal
common_fcreate_silent /pg/mods/containers/primary
common_fcreate_silent /pg/mods/containers/community
rm -rf /pg/tmp/appstoinstall.list && touch /pg/tmp/appstoinstall.list
touch /pg/tmp/list.tmp
case $typed in
    1 ) sapp="primary" && pull_actions && ls -p /pg/mods/containers/$sapp/ | grep -v / > "/pg/tmp/list.tmp" && apps_interface ;;
    2 ) sapp="community" && pull_actions && ls -p /pg/mods/containers/$sapp/ | grep -v / > "/pg/tmp/list.tmp" && apps_interface ;;
    3 ) sapp="personal" && pull_actions && personal_blank && ls -p /pg/mods/containers/$sapp/ | grep -v / > "/pg/tmp/list.tmp" && apps_interface ;;
    4 ) repos_part1 && exit ;;
    6 ) apps_default_interface ;;
    5 ) shield_setup ;;
    9 ) app="primary" && ls -p /pg/mods/containers/$sapp/ | grep -v / > "/pg/tmp/list.tmp" && apps_interface ;;
    z ) start_menu ;;
    Z ) start_menu ;;
    * ) apps_menu ;;
esac

}
