#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_gen_lists() {

ls -p /pg/mods/containers/$app_select/"$p" | grep -v / > "/pg/tmp/$p.list"

while read p; do
  fmt -w 79 "/pg/tmp/$p.list" > "/pg/tmp/$p.wrap"
  #sed -i -e "/pgui/d" "$set_path"
done </pg/tmp/list.tmp

}
