#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
apps_command() {

# CMD EXPORT ###################################################################
cat <<- EOF > "/bin/pg-$app"
#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###

source /pg/mods/functions/.master.sh
$app

EOF
}
