#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
common_fcreate() {
  if [[ ! -e "$1" ]]; then
    mkdir -p "$1"
    chown 1000:1000 "$1"
    chmod 0775 "$1"; fi
    echo "Generated Folder: $1"
}
