#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
common_install() {
touch /pg/var/install/"${1}".stored
start=$(cat /pg/var/install/"${1}")
stored=$(cat /pg/var/install/"${1}".stored)
if [ "$start" != "$stored" ]; then
  $1
  cat /pg/var/install/"${1}" > /pg/var/install/"${1}".stored;
fi
}
