#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
container_traefik () {

traefik_menu_start_setup

common_main /pg/data/$pgrole/cname.traefik "$app" cname_fill

if [[ ! -e "/pg/data/$pgrole/shield.setting" ]]; then
apps_interface_start
cat /pg/var/defaults/default.port > "/pg/data/$pgrole/shield.setting"; fi

if [[ $(cat "/pg/data/$pgrole/shield.setting") == "ON" ]]; then
container_traefik="  traefik.enable: 'true'
          traefik.port: '$traefik_extport'
          traefik.frontend.rule: 'Host:$cname_fill.$domain'
          traefik.frontend.auth.forward.address: 'http://shield:4181'
          traefik.frontend.headers.SSLHost: '$domain'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'"
else
  container_traefik="  traefik.enable: 'true'
          traefik.port: '$traefik_extport'
          traefik.frontend.rule: 'Host:$cname_fill.$domain'
          traefik.frontend.headers.SSLHost: '$domain'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'"
fi
}
