#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
container_start () {

container_start="
    - name: 'Deploying $pgrole'
      docker_container:
        name: '$pgrole'
        image: '$image'
        pull: yes"
}
