#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
container_core() {

domain="test.com"

common_fcreate_silent /pg/data/$pgrole
common_fcreate_silent /pg/var/apps

container_paths=$(cat "/pg/tmp/container.path")
container_permissions=$(cat "/pg/tmp/container.permissions")

container_header
container_start
container_permissions
container_traefik
container_ending

}
