#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
container_ending () {

container_ending="volumes:
          $container_paths
        state: started
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '$pgrole'"
}
