#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
container_permissions () {
  cpath_check=$(cat /pg/tmp/container.permissions)
  if [[ "$cpath_check" == "" ]]; then echo "$1: '$2'" >> /pg/tmp/container.permissions
else echo "          $1: '$2'" >> /pg/tmp/container.permissions; fi
}
