#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
container_ending () {

container_ending="volumes:
          $container_paths
        state: started
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '$pgrole'"

# CMD EXPORT ###################################################################
chown -R 1000:1000 "/bin/pg-$pgrole"
chmod -R 0755 "/bin/pg-$pgrole"

cat <<- EOF > "/bin/pg-$pgrole"
#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###

source /pg/mods/functions/.master.sh
app=$pgrole
sapp="EXPRESS"
express="ON"

apps_interface_start
apps_interface_sub

EOF
}
