#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
container_traefik () {

traefik_menu_start_setup

container_traefik="          traefik.frontend.auth.forward.address: 'http://shield:4181'
          traefik.enable: 'true'
          traefik.port: '$traefik_extport'
          traefik.frontend.rule: 'Host:$pgrole.$domain'
          traefik.frontend.headers.SSLHost: '$domain'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'"
}
