#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_gdrive_menu_password () {

drives_menu_start_setup

common_message "🚀  GDrive - Encryption Password Interface" "
💬  Further Explanation? Visit ~ http://drives.plexguide.com
------------------------------------------------------------------------------
NOTE: Do not forget your passwords! Forgetting results in 100% data loss! We
are not kidding! Utilizing a different password for PASSWORD2 will make your
drive more secure, but both can be the same password. Again, do not lose them!

[1] Password 1       : [$gpassword1]
[2] Password 2 (SALT): [$gpassword2]
------------------------------------------------------------------------------
[Z] Exit Interface
"
common_number

case $typed in
    1 ) gdrivepw=1 && drives_gdrive_menu_password_interface && exit ;;
    2 ) gdrivepw=2 && drives_gdrive_menu_password_interface && exit ;;
    z ) drives_gdrive_menu && exit ;;
    Z ) drives_gdrive_menu && exit ;;
    * ) drives_gdrive_menu_password && exit ;;
esac

}
