#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_key_generation () {

drives_menu_start_setup

upload_projectid=$(cat /pg/var/drives/shared/${drive_upload}/project.name)
upload_email=$(cat /pg/var/drives/shared/${drive_upload}/e.mail)

gcloud config set project ${upload_projectid}
pool_quota=$(gcloud --account=${upload_email} iam service-accounts list | awk '{print $1}' | sort -u | cut -d'?' -f2- | rev | cut -d'?' -f2- | rev | grep "plexguide" | sort -V | awk 'END { print }' | awk -F- '{ print $NF}')
if [[ "$pool_quota" == "" ]]; then left_quota=100; else left_quota="$((100-$pool_quota))"; fi

if [[ "$left_quota" -lt "33" ]]; then maxkeys=$left_quota; else maxkeys=33; fi
if [[ "$left_quota" -lt "4" ]]; then message=1; else message=0; fi
if [[ "$left_quota" == "100" ]]; then pool_quota=0; fi

if [[ "$message" == 0 ]]; then
common_message "🚀  Drives - Key Management Interface" "
💬  Further Explanation? Visit ~ https://plexguide.com/wiki/drives/
------------------------------------------------------------------------------
Generate how many keys? [ 4 - ${maxkeys} ]

4  Keys = 3 TB      8  Keys = 6 TB <---- Realistic Amount
12 Keys = 9 TB      20 Keys = 15TB <---- GCE Feeder
33 Keys = 25TB

[$pool_quota] of 100 - KeyPool Quota Utilized

Manage Keys:
https://console.cloud.google.com/apis/credentials?authuser=1&folder=&organizationId=&project=$upload_projectid
------------------------------------------------------------------------------
[Z] Exit Interface
"
else
common_message "🚀  Drives - Key Management Interface" "
💬  Further Explanation? Visit ~ https://plexguide.com/wiki/drives/
------------------------------------------------------------------------------
⛔️ CANNOT DEPLOY ANY KEYS! KEYS MAXED OUT!

In order to deploy more keys using this same project, delete some service keys
via PG's options or by visiting the following link below:

https://console.cloud.google.com/apis/credentials?authuser=1&folder=&organizationId=&project=$upload_projectid

[$pool_quota] of 100 - KeyPool Quota Utilized"
common_confirm
drives_menu_start
fi

read -p "↘️  Generate How Many Keys? | Press [ENTER]: " typed < /dev/tty
if [[ "$typed" == "Z" || "$typed" == "z" ]]; then drives_menu_start && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: CANNOT BE BLANK" && common_confirm && drives_key_generation && exit; fi
if [[ "$typed" -lt "4" ]]; then common_message "⛔️  WARNING: REQUIRES 4 OR MORE KEYS" && common_confirm && drives_key_generation && exit; fi
if [[ "$typed" -gt "${maxkeys}" ]]; then common_message "⛔️  WARNING: EXCEEDS MAX KEYS" && common_confirm && drives_key_generation && exit; fi

common_fcreate_silent "/pg/var/keys/${drive_upload}"
rm -rf "/pg/var/keys/${drive_upload}/*"
echo "$typed" > "/pg/var/keys/${drive_upload}/key.count"

count=$(gcloud --account=${upload_email} iam service-accounts list | awk '{print $1}' | sort -u | cut -d'?' -f2- | rev | cut -d'?' -f2- | rev | grep "plexguide" | sort -V | awk 'END { print }' | awk -F- '{ print $NF}')

#key_checker=$(gcloud --account=${upload_email} iam service-accounts list | grep "\(plexguide-${count}\)\>")
#if [[ "$key_checker" != "" ]]; then
##  gcloud --account=${upload_email} iam service-accounts delete $check2
#fi

rm -rf /pg/var/drives/shared/${drive_upload}/blitz/* /pg/var/drives/shared/${drive_upload}/shared.emails
if [[ "$count" == "" ]]; then count=0; fi
keys=$typed
countdown=$typed
tally=0

while [ "$countdown" != "0" ]; do
     ((count++))
     ((tally++))
     ((countdown--))
     common_header "💾  PG KEY [$count] - $tally of $keys" && sleep 1
     gcloud iam service-accounts create ${drive_upload}-${count} --display-name “plexguide-$count”
     gcloud iam service-accounts keys create /pg/var/keys/${drive_upload}/plexguide_$count --iam-account ${drive_upload}-${count}@${upload_projectid}.iam.gserviceaccount.com --key-file-type="json"
     ${drive_upload}-${count}@${upload_projectid}.iam.gserviceaccount.com >> /pg/var/drives/shared/${drive_upload}/shared.emails
     drives_key_build
done <"/pg/var/keys/${drive_upload}/key.count"

common_message "🚀  Keys - Process Complete! Add E-Mails to the SD Next!"
common_confirm
drives_menu_start
}
