#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_share_name_label_select () {

drives_menu_start_setup

if [[ "$project_name" != "NOT-SET" ]]; then priorproject=$project_name
else priorproject="NOT-SET"; fi

common_message "🚀  Project Interface - $sdselect | Current Project: $priorproject

[1] Utilize | Existing project
------------------------------------------------------------------------------
[C] Create  | New project & set
[D] Destory | An existing project
------------------------------------------------------------------------------
[Z] Exit"

common_number

case $typed in
    1 ) drives_share_name_label_utilize_project ;;
    C ) drives_share_name_label_create_project ;;
    c ) drives_share_name_label_create_project ;;
    d ) common_header "🚀  Feature will be added when most PGX coding complete!" && common_confirm && drives_share_name_label_select && exit ;;
    D ) common_header "🚀  Feature will be added when most PGX coding complete!" && common_confirm && drives_share_name_label_select && exit ;;
    z ) drives_share_manage_module && exit ;;
    Z ) drives_share_manage_module && exit ;;
    * ) drives_share_name_label_select && exit ;;
esac

}
