#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_uploader_rclone() {

# execution of movement
rclone moveto "$longkey" $drive_upload:"${shortkey}" \
--config="$rclone_upload" \
--log-file="/pg/var/transport/${b}/rclone.log" \
--log-level=INFO --stats-one-line --stats=1s --stats-file-name-length=0 &>/dev/null &
}
