#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_deploy_unity() {

drives_menu_start_setup

################################################################################
unity_script_path="/pg/var/drives/unity.sh"
  unity_build=""
  unity_crypt="c"

if [[ "$gd_final" == "VALID" ]]; then unity_build=$(echo ${unity_build}/pg/gd=NC:); fi
if [[ "$gc_final" == "VALID" ]]; then unity_build=$(echo ${unity_build}/pg/gc=NC:); fi

while read p; do
  unity_build=$(echo ${unity_build}/pg/${p}=NC:)
done </pg/tmp/drives.list

while read p; do
  unity_build=$(echo ${unity_build}/pg/${p}${unity_crypt}=NC:)
done </pg/tmp/edrives.list
  unity_build=${unity_build%?}

# add know programs as read only while sitting in /pg/complete
drives_known_programs

# mergerfs -o func.getattr=newest,category.create=ff,direct_io,use_ino,atomic_o_trunc,big_writes,default_permissions,splice_move,splice_read,splice_write,allow_other,sync_read,minfreespace=0,umask=002,uid=1000,gid=1000,fsname=pgunity,nonempty \

# builds unity script
cat <<- EOF > "$unity_script_path"
sleep 3

chown -R 1000:1000 "/pg/downloads"
chmod -R 755 "/pg/downloads"
chown -R 1000:1000 "/pg/transfer"
chmod -R 755 "/pg/transfer"

mergerfs -o sync_read,auto_cache,dropcacheonclose=true,use_ino,allow_other,func.getattr=newest,category.create=ff,minfreespace=0,fsname=pgunity \
/pg/transport=RW:$unity_build /pg/unity
EOF
################################################################################
service_path="/etc/systemd/system/unity.service"

if [[ -e "$service_path" ]]; then
common_header "💾  NOTICE:  Stopping/Disabling OLD Unity Service"; sleep 1
systemctl daemon-reload && systemctl stop unity && systemctl disable unity && rm -rf "$service_path"; fi

cat <<- EOF > "$service_path"

[Unit]
Description=PGUnity
After=multi-user.target

[Service]
Type=simple
User=0
Group=0
ExecStart=/bin/bash $unity_script_path
ExecStop=/bin/fusermount -uzq /pg/unity
TimeoutStopSec=60
KillMode=process
RemainAfterExit=yes

ExecStop=/bin/fusermount -uz /pg/unity > /dev/null
TimeoutSec=60
User=0
Group=0
Restart=on-abort
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3


[Install]
WantedBy=multi-user.target
EOF

fusermount -u -q /pg/unity
common_fcreate_silent /pg/unity
common_header "💾  NOTICE:  Starting/Enabling NEW Service - Unity" && sleep 1
systemctl daemon-reload && systemctl enable unity | fmt -w 79 && systemctl restart unity

common_header "💾  ENABLED:  MergerFS Drive ~ /pg/unity deployed!" && sleep 1.5
}
