#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_share_menu_password () {

drives_menu_start_setup

common_message "🚀  SDrive - Encryption Password Interface" "
💬  Further Explanation? Visit ~ https://plexguide.com/wiki/drives/
------------------------------------------------------------------------------
NOTE: Do not forget your passwords! Forgetting results in 100% data loss! We
are not kidding! Utilizing a different password for PASSWORD2 will make your
drive more secure, but both can be the same password. Again, do not lose them!

[1] Password 1       : [$spassword1]
[2] Password 2 (SALT): [$spassword2]
------------------------------------------------------------------------------
[Z] Exit Interface
"
common_number

case $typed in
    1 ) sdrivepw=1 && drives_share_menu_password_interface && exit ;;
    2 ) sdrivepw=2 && drives_share_menu_password_interface && exit ;;
    z ) drives_share_manage_module && exit ;;
    Z ) drives_share_manage_module && exit ;;
    * ) drives_share_menu_password && exit ;;
esac

}
