#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_basic_deploy_transporter() {

  # transport process
  merit_count=0
  while read b; do
    echo "TEST2 - ${b}"
    echo "SHORT - $shortkey and LONG - $longkey"
    dircheck=$(ls "/pg/var/transport/${b}")
    if [[ "$dircheck" == "" ]]; then

      # moves along the merit list
      let "merit_count=merit_count+1"
      echo "merit: $merit_count"
      rclone_long=$(sed "${merit_count}q;d" /pg/var/upload/upload.long)

      if [[ "$rclone_long" != "" ]]; then
        rclone_short=$(sed "${merit_count}q;d" /pg/var/upload/upload.short)

          # execute if not empty
          echo $b
          common_fcreate_silent "/pg/var/transport/${b}"
          mkdir -p "/pg/var/transport/${b}"
          touch "/pg/var/transport/${b}/rclone.log"
          echo "$rclone_short" > "/pg/var/transport/${b}/key.short"
          echo "$rclone_long" > "/pg/var/transport/${b}/key.long"
          shortkey=$(cat /pg/var/transport/${b}/key.short)
          longkey=$(cat /pg/var/transport/${b}/key.long)
          if [[ "$longkey" != "" ]]; then

            #removes junk vars / may end up tossing
            #rm -rf "/pg/var/drives/sizes/$shortkey.1" cat "/pg/var/drives/sizes/$shortkey.2"

            echo "TRANSFERING GSUITE - $longkey"
            rclone moveto "$longkey" gd:"$shortkey" \
              --config=/pg/var/drives/gd/gd.conf \
              --log-file="/pg/var/transport/${b}/rclone.log" \
              --log-level=INFO --stats=5s --stats-file-name-length=0 &>/dev/null &
      fi; fi; fi
      # prevents overwhelming the system
      sleep .5
  done </pg/var/upload/slot.list
}
