#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_share_active_count () {

mkdir -p /pg/var/drives/shared/ /pg/var/drives/e.tokens

find_shared_check=$(find /pg/var/drives/shared/ -mindepth 1 -type d)
if [[ "$find_shared_check" != "" ]]; then find /pg/var/drives/shared/*/*.token > /pg/tmp/active.count; else
touch /pg/tmp/active.count; fi

rm -rf /pg/var/drives/valid.drives

a=0
while read p; do
  checkvalidcount=$(cat $p)
  if [[ "$checkvalidcount" == "VALID" ]]; then
  echo "$p" | cut -d'/' -f7- | rev | cut -c7- | rev >> /pg/var/drives/valid.drives
  ((a++)); fi
done </pg/tmp/active.count

ls -la /pg/var/drives/e.tokens | awk '{print $9}' | tail -n +4 > /pg/var/drives/evalid.drives

echo "$a" > /pg/var/drives/shared/active.count
}
