#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_menu_storage_method() {

drives_menu_start_setup

common_message "🚀  Drives - Storage Method" "
💬  Further Explanation? Visit ~ https://plexguide.com/wiki/drives/
------------------------------------------------------------------------------

Upload Method

[1] READ-ONLY      | None - Useful for a READ-ONLY Server (2nd PLEX & ETC)
[2] Drives Basic   | 750GB Daily Cap Upload to To Target Drive
[3] Drives PGBlitz | NOT READY
[4] Drives Local   | NOT READY
------------------------------------------------------------------------------
[Z] Exit Interface
"
common_number

case $typed in
    1 ) echo "READ-ONLY" > /pg/var/drives/storage.method && drives_menu_start && exit ;;
    2 ) echo "BASIC" > /pg/var/drives/storage.method && drives_menu_start && exit ;;
    #3 ) echo "PGBLITZ" > /pg/var/drives/storage.method && drives_menu_start && exit ;;
    #4 ) echo "LOCAL" > /pg/var/drives/storage.method && drives_menu_start && exit ;;
    z ) drives_menu_start && exit ;;
    Z ) drives_menu_start && exit ;;
    * ) drives_menu_storage_method && exit ;;
esac

}
