#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_known_programs() {

path_known_programs="/pg/var/upload"; mkdir -p "$path_known_program"

# known programs
echo "nzbget" > "$path_known_programs"/program.list
echo "rutorrent" >> "$path_known_programs"/program.list

# sets things up
rm -rf "$path_known_programs"/program.unity

# builds a temp file for pgunity to add Read Only's incase
while read t; do
    echo -n "/pg/complete/$t=NC" >> "$path_known_programs"/program.unity
 done <"$path_known_programs"/program.list

}
