#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_basic_deploy() {

# pulls key variables
drives_menu_start_setup

# declare variables and remove
path_upload="/pg/var/upload"
mkdir -p $path_upload && rm -rf "$path_upload"/{upload.short,upload.long}
merit_count=0

while read z; do
echo "$(find /pg/complete/$z -type f -printf "\n%AT %p" | awk '{print $2}' | tail -n +2)" >> "$path_upload"/upload.long

# generates short and long paths for upload
  while read p; do
      remove_path="/pg/complete/$z"
      valid=$(echo $p | grep $z)
        if [[ "$valid" != "" ]]; then
          echo "${p#*$remove_path}" >> "$path_upload"/upload.short; fi
    done <"$path_upload"/upload.long
done <"$path_upload"/program.list

echo "TESTING"
echo "$(ls /pg/transport)" > /pg/var/upload/slot.list

while read b; do
  echo "TEST2 - $b"
  if [[ -e "$(ls /pg/transport/$b)" ]]; then

    # moves along the merit list
    let "merit_count=merit_count+1"
    rclone_long=$(sed "${merit_count}q;d" /pg/var/upload/upload.long)
    rclone_short=$(sed "${merit_count}q;d" /pg/var/upload/upload.short)

    echo "$rclone_long - $rclone_short"
      # execute if not empty
      echo "TEST3 - $rclone_long"
      if [[ "$rclone_long" != "" ]]; then
        rclone moveto "$rclone_long" gd:"$rclone_short" \
          --config=/pg/var/drives/gd/gd.conf
      fi
  fi
done </pg/var/upload/slot.list

}
