#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_share_crypt_menu () {

drives_menu_start_setup

common_message "🚀  SDrive - Encryption Selection Interface" "
💬  Further Explanation? Visit ~ https://plexguide.com/wiki/drives/
------------------------------------------------------------------------------
Enable to read and store (not required) to an encrypted drive?

[N] No
[Y] Yes
------------------------------------------------------------------------------
[Z] Exit Interface
"
common_number

case $typed in
    Y ) echo "YES" > /pg/var/drives/shared/$sdselect/sd.crypt && drives_share_manage_module && exit ;;
    y ) echo "YES" > /pg/var/drives/shared/$sdselect/sd.crypt && drives_share_manage_module && exit ;;
    N ) echo "NO" > /pg/var/drives/shared/$sdselect/sd.crypt && drives_share_manage_module && exit ;;
    n ) echo "NO" > /pg/var/drives/shared/$sdselect/sd.crypt && drives_share_manage_module && exit ;;
    z ) drives_share_manage_module && exit ;;
    Z ) drives_share_manage_module && exit ;;
    * ) gdrives_share_crypt_menu  && exit ;;
esac

}
