#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_gdrive_clientid() {

temp_path="/pg/var/drives/gd/gd.clientid"
priorentry=$(cat $temp_path)

common_message "🚀 PlexGuide | GDrive Client-ID Interface" "
💾 Client-ID for GDrive? Visit ~ https://console.developers.google.com

Prior Info Saved (If Any): $priorentry
[Z] To Cancel and Go Back
"

read -p "↘️  New GDrive Client ID? | Press [Enter]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then drives_gdrive_menu && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && drives_gdrive_clientid && exit; fi

echo $typed > $temp_path
common_message "💾  $typed - Client ID Set!"
common_confirm && drives_gdrive_menu && exit

}
