#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_basic_upload () {

drives_menu_start_setup

fmt -w 79 "/pg/var/drives/shared/pg.list" > "/pg/tmp/sdlist.wrap"
if [[ "$gdtokeninfo" == "VALID" ]]; then echo -n "gd" >> /pg/tmp/sdlist.wrap; fi
if [[ -e "/pg/var/drives/e.tokens"; then "gc" >> /pg/tmp/sdlist.wrap ]]; fi
sdlist=$(cat /pg/tmp/sdlist.wrap)

common_message "🚀  Drive Select Upload - Management Interface" "
💾 NOTE: gd = Google Drive | {name}c <<< equals encrypted drive

$sdlist

[Z] Exit Interface"

read -p '↘️  Type Drive to Upload To | Press [ENTER]: ' typed < /dev/tty
  if [[ "$typed" == "z" || "$typed" == "Z" ]]; then drives_share_menu; exit; fi

existcheck=$(echo $sdlist | grep "$typed" -w)
  if [ -z "$existcheck" ]; then echo "";
  read -p '⛔️  '$typed' <<< does not exist or has been selected | Press [ENTER]' badinput < /dev/tty
  drives_share_manage; fi

echo $typed > /pg/var/drives/basic.upload
drives_share_menu
}
