#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_basic_deploy_slot_check() {
while read zz; do
  if [[ -e "/pg/var/transport/${zz}/key.long" ]]; then
    delete_check=$(cat /pg/var/transport/${zz}/key.long)
    if [[ "$delete_check" != "" ]]; then rm -rf /pg/var/transport/${m}/* && echo "FREED - {$zz}"; fi
  fi
done <"$path_upload"/slot.list
}
