#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_share_clientid() {

temp_path="/pg/var/drives/shared/$sdselect/sd.clientid"
priorentry=$(cat $temp_path)

common_message "🚀 PlexGuide | SDrive: $sdselect ClientID Interface" "
💾 Client-ID for SDrive? Visit ~ https://console.developers.google.com

Prior Info Saved (If Any): $priorentry
[Z] To Cancel and Go Back
"

read -p "↘️  New SDrive Client ID? | Press [Enter]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then drives_share_manage_module && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && drives_share_clientid && exit; fi

echo $typed > $temp_path
common_message "💾  $typed - Client ID Set!"
common_confirm && drives_share_manage_module && exit

}
