#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_known_programs() {

mkdir -p /pg/var/upload 
path_known_programs="/pg/var/upload"

# known programs
echo "nzbget" > "$path_known_programs"/program.list
echo "rutorrent" >> "$path_known_programs"/program.list

# sets things up
rm -rf "$path_known_program"/program.unity

# builds a temp file for pgunity to add Read Only's incase
while read t; do
    echo -n "/pg/complete/$t=NC" >> "$path_known_program"/program.unity
 done <"$path_known_program"/program.list

add_to_unity=$(cat "$path_known_programs"/program.unity)
unity_build=$(echo ${unity_build}${add_to_unity})

}
