#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_key_email() {

  #drives_menu_start_setup
  #touch /pg/var/drives/shared/${drive_upload}/emails.unlocked

  #rm -rf /pg/var/.emailbuildlist 1>/dev/null 2>&1
  #rm -rf /pg/var/.emaillist  1>/dev/null 2>&1

  #ls -la /pg/var/.blitzkeys | awk '{print $9}' | tail -n +4 > /pg/var/.emailbuildlist
  #while read p; do
  #  cat /pg/var/.blitzkeys/$p | grep client_email | awk '{print $2}' | sed 's/"//g' | sed 's/,//g' >> /pg/var/.emaillist
  #done </pg/var/.emailbuildlist

  #tee <<-EOF
  #━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  #🚀 EMail Share Generator ~ pgclone.pgblitz.com
  #━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  #PURPOSE: Share out the service accounts for the TeamDrives. Failing to do
  #so will result in PGBlitz Failing!
  #Shortcut to Google Team Drives >>> td.pgblitz.com
  #NOTE 1: Share the E-Mails with the CORRECT TEAMDRIVE: $sdname
  #NOTE 2: SAVE TIME! Copy & Paste the all the E-Mails into the share!"
  #EOF
  #cat /pg/var/.emaillist
  #echo ""
  #echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  #read -rp '↘️  Completed? | Press [ENTER] ' typed < /dev/tty
  #clonestart

drives_menu_start
}
