#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_share_add_menu () {

## TODO - Prevent Duplicate Entries / Prevent Known Folders such as mods, pg

drives_menu_start_setup

temp_path="/pg/var/drives/gd/gd.clientid"
priorentry=$(cat $temp_path)

common_message "🚀 PlexGuide | ADD ~ ShareDrive Interface" "
💾 No Share Drives on your GSuite?
   Visit: https://drive.google.com/drive/shared-drives

NOTE: Does NOT have to be the name of your exact ShareDrive, but recommended
for better tracking. Must be a whole word, lowercase, and must be between
2 - 14 letters in length. DO NOT USE SPECIAL CHARACTERS; may cause failure
on your end!

[Z] To Cancel and Go Back
"

read -p "↘️  Name an Existing ShareDrive | Press [Enter]: " typed < /dev/tty

typed=$(echo $typed | awk '{print $1}')
typed=$(echo "$typed" | awk '{print tolower($0)}')
lettercount=$(echo $typed | wc -c)

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then drives_share_menu && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && drives_share_add_menu && exit; fi

if [[ "$lettercount" -gt "15" || "$lettercount" -lt "3" ]]; then
common_message "TYPED: $typed" && common_message "⛔️  WARNING: Is less than 2 or more than 14 characters! Try Again!"
common_confirm && drives_share_add_menu && exit; fi

drives_blacklist="/pg/tmp/drives_blacklist" && ls -la /pg | awk '{print $9}' > $drives_blacklist
echo "pg" >> $drives_blacklist && echo "plexguide" >> $drives_blacklist echo "unity" >> $drives_blacklist
blacklist_final=$(cat $drives_blacklist | grep "\<$typed\>")
if [[ "$blacklist_final" != "" ]]; then
common_message "⛔️  WARNING: $typed exists under /pg & cannot use! Try Again!" && common_confirm && drives_share_add_menu && exit; fi

common_message "💾  $typed - SD added to PG! Go Configure it!"
common_fcreate_silent /pg/$typed

# Sort List
echo "$typed" >> /pg/var/drives/shared/pg.list
temp57=$(cat /pg/var/drives/shared/pg.list | sort )
echo "$temp57" > /pg/var/drives/shared/pg.list

common_confirm && drives_share_menu && exit

}
