#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_basic_deploy_slot_check() {

  if [[ -e "/pg/var/transport/${m}/key.long" ]]; then
    #echo "/pg/var/transport/${m}/key.short"
    #shortkey=$(cat "/pg/var/transport/${m}/key.short")
    #shortkey=$(echo ${shortkey} | cut -c 2-)
    # delete_check=$(rclone ls --config /pg/var/drives/gd/gd.conf --max-depth 1 gd: | grep "${shortkey}")
    delete_check=$(cat /pg/var/transport/${m}/key.long)
    if [[ "$delete_check" != "" ]]; then rm -rf /pg/var/transport/${m}/* && echo "FREED - {$m}"; fi
  fi
}
