#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_basic_deploy() {

# create file folder for sizes
  rm -rf /pg/var/drives/sizes && common_fcreate_silent /pg/var/drives/sizes/

# clears upload list
  rm -rf /pg/var/transport/*

# pulls key variables
drives_menu_start_setup

# declare variables and remove
path_upload="/pg/var/upload"
path_exempt_programs="/pg/var/upload"; mkdir -p "$path_exempt_programs"
mkdir -p $path_upload && rm -rf "$path_upload"/{upload.short,upload.long}

#exempt file locations
find /pg/complete/ -type f -mmin +1 -printf "\n%AT %p" | sort -k1 | cut -d " " -f 2- | tail -n +2 > "$path_upload"/upload.long

#drives_deploy_exempt
while read l; do
sed -i -e "/$l/d" "$path_upload"/upload.long
done <"$path_exempt_programs"/exempt.list

# generates short files
  while read p; do
      remove_path="/pg/complete"
          echo "${p#*$remove_path}" >> "$path_upload"/upload.short
  done <"$path_upload"/upload.long

echo "$(ls /pg/var/transport)" > /pg/var/upload/slot.list

# starts the upload process 
drives_basic_deploy_transporter

# if completed, then free slot for upload
while read m; do
  drives_basic_deploy_slot_check &>/dev/null &
done </pg/var/upload/slot.list

# repeat
drives_basic_deploy
}
