#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_known_programs() {

# setting things up
path_known_programs="/pg/var/upload"; mkdir -p "$path_known_program"
rm -rf "$path_known_programs"/program.unity

# known programs
echo "nzbget" > "$path_known_programs"/program.list
echo "rutorrent" >> "$path_known_programs"/program.list

# builds a temp file for pgunity to add Read Only's incase
while read t; do
    echo -n ":/pg/complete/$t=NC" >> "$path_known_programs"/program.unity
    common_fcreate_silent /pg/complete/$t
 done <"$path_known_programs"/program.list

# adds known programs to pgunity prior to deployment
add_to_unity=$(cat "$path_known_programs"/program.unity)
unity_build=$(echo ${unity_build}${add_to_unity})

}
