#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_basic_deploy_transporter() {

  # transport process
  merit_count=0
  while read b; do
    echo "FLAG 2 - $b"
    shortkey="" && longkey=""
    if [[ ! -e "/pg/var/transport/${b}/key.long" ]]; then

      # moves along the merit list
      let "merit_count=merit_count+1"
      #echo "merit: $merit_count"

      rclone_long=$(sed "${merit_count}q;d" /pg/var/upload/upload.long)
      if [[ "$rclone_long" != "" ]]; then
        rclone_short=$(sed "${merit_count}q;d" /pg/var/upload/upload.short); fi

      if [[ "$rclone_short" != "" ]]; then
          common_fcreate_silent "/pg/var/transport/${b}"
          mkdir -p "/pg/var/transport/${b}"
          touch "/pg/var/transport/${b}/rclone.log"
          echo "$rclone_short" > "/pg/var/transport/${b}/key.short"
          echo "$rclone_long" > "/pg/var/transport/${b}/key.long"

          shortkey=$(cat /pg/var/transport/${b}/key.short)
          longkey=$(cat /pg/var/transport/${b}/key.long)
          echo "SLOT - $b - SHORT"; fi

          drives_basic_deploy_transporter_execute; fi
          sleep .5
  done <"$path_upload"/left.upload
}
