#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
drives_gdrive_crypt_menu () {

drives_menu_start_setup

common_message "🚀  GDrive - Encryption Selection Interface" "
💬  Visit ~ https://plexguide.com/wiki/drives/
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Enable to read and store (not required) to an encrypted drive?

[N] No
[Y] Yes
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface
"
common_number

case $typed in
    Y ) echo "YES" > /pg/var/drives/gd/gd.crypt && drives_gdrive_menu && exit ;;
    y ) echo "YES" > /pg/var/drives/gd/gd.crypt && drives_gdrive_menu && exit ;;
    N ) echo "NO" > /pg/var/drives/gd/gd.crypt && drives_gdrive_menu && exit ;;
    n ) echo "NO" > /pg/var/drives/gd/gd.crypt && drives_gdrive_menu && exit ;;
    z ) drives_gdrive_menu && exit ;;
    Z ) drives_gdrive_menu && exit ;;
    * ) gdrives_gdrive_crypt_menu  && exit ;;
esac

}
