#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_drivecheck() {
  leftover=$(df / --local | tail -n +2 | awk '{print $4}')
  if [[ "$leftover" -lt "75000000" ]]; then

common_message "⛔️  Local Disk Space Warning!" "
We noticed that you have less than 75GB of space! Utilizing PG for large
downloads, large backups, and/or running a large Plex Server may cause the
server to crash without enough diskspace!

PRESS CTRL+Z to STOP the Installation
"
    common_confirm
  fi
}
