#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_oldpg() {

	touch /pg/var/pg.number
	file="/pg/var/pg.number"
	if [ -e "$file" ]; then
	  check="$(cat /pg/var/pg.number | head -c 1)"
	  if [[ "$check" == "5" || "$check" == "6" || "$check" == "7" || "$check" == "8" || "$check" == "9" ]]; then

	tee <<-EOF

	━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	🌎  INSTALLER BLOCK: Notice
	━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
	We detected PG Version $check is running! Per the instructions, this new PG
	must be installed on a FRESH BOX! Exiting!
	━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

	EOF
	    exit; fi; fi
}
