#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_nvidia() {

	common_header "⌛ INSTALLING: Nvidia Drivers"; sleep 2
	ansible-playbook /pg/mods/ymls/pg.yml --tags nvidia

}
