#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_mergerfs() {

	common_header "⌛ INSTALLING: MergerFS"; sleep 2
	ansible-playbook /pg/mods/ymls/pg.yml --tags mergerfsinstall

}
