#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_rclone() {

	common_header "⌛ INSTALLING: RClone"; sleep 2
	ansible-playbook /pg/mods/ymls/pg.yml --tags rcloneinstall

}
