#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
install_dependency () {
  ospgversion=$(cat /pg/var/os.var)

  common_header "⌛ REQUIRED: Installing Key $ospgversion Dependencies"; sleep 2
  if [ "$ospgversion" == "Ubuntu" ]; then
    ansible-playbook /pg/mods/ymls/dep_ubuntu.yml;
  else
    ansible-playbook /pg/mods/ymls/dep_debian.yml; fi
}
