#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
shield_setup_start_uc() {
  if [[ -e "/pg/var/shield/user.list" ]]; then
  wc -l /pg/var/shield/user.list | awk '{print $1}' > /pg/var/shield/user.count; fi
  if [[ -e "/pg/var/shield/user.list" && $(cat /pg/var/shield/user.list) == "" ]]; then
  echo 0 > /pg/var/shield/user.count; fi
}

shield_setup_start() {

shield_setup_start_uc
common_fcreate_silent /pg/var/shield
common_main /pg/var/shield/web.client NOT-SET shield_wc
common_main /pg/var/shield/web.secret NOT-SET shield_ws
common_main /pg/var/shield/user.count 0 shield_uc
common_main /pg/var/shield/user.list "" shield_ul

oauth_docker=$(docker ps | grep "oauth")
if [[ "$oauth_docker" == "" ]]; then oauth_display="NOT-DEPLOYED"; else
oauth_display="DEPLOYED"; fi

if [[ "$shield_wc" != "NOT-SET" ]]; then shield_wc_display="SET"
else shield_wc_display="NOT-SET"; fi

if [[ "$shield_ws" != "NOT-SET" ]]; then shield_ws_display="SET"
else shield_ws_display="NOT-SET"; fi

# WARNINGS #####################################################################
if [[ $(docker ps | grep "\<traefik\>") != "traefik" ]]; then
shield_warning="
⛔️ WARNING: Traefik Not Deployed & Will Fail"; fi
# forces function refresh of function output ###################################
bash /pg/mods/functions/.other_apps.sh

}
