#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
shield_setup() {

shield_setup_start

# WebClient ID Entry ###########################################################
shield_web_client() {
temp_path="/pg/var/shield/web.client"
priorentry=$(cat $temp_path)

common_message "🚀 PlexGuide | Shield: WebClient-ID Interface" "💾 WebClient-ID for Shield? Visit ~ https://console.developers.google.com

Prior Info Saved (If Any): $priorentry
[Z] Cancel"

read -p "↘️  New WebClient-ID? | Press [ENTER]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then shield_setup && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && shield_web_client && exit; fi

echo $typed > $temp_path
common_message "💾  $typed - WebClient Set!"
common_confirm && shield_setup && exit
}

# WebClient ID Entry ###########################################################
shield_web_secret() {
temp_path="/pg/var/shield/web.secret"
priorentry=$(cat $temp_path)

common_message "🚀 PlexGuide | Shield: WebSecret-ID Interface" "💾 WebSecret-ID for Shield? Visit ~ https://console.developers.google.com

Prior Info Saved (If Any): $priorentry
[Z] Cancel"

read -p "↘️  New WebSecret-ID? | Press [ENTER]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then shield_setup && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && shield_web_secret && exit; fi

echo $typed > $temp_path
common_message "💾  $typed - WebSecret Set!"
common_confirm && shield_setup && exit
}

# Users Management - Main Interface ############################################
shield_user_interface() {
shield_setup_start

  # Updates Authorized User Count
  shield_setup_start_uc
  shield_uc=$(cat /pg/var/shield/user.count)

common_message "🚀  Shield User Interface" "💬 Current Authorized Users: $shield_uc

[1] User: Add
[2] User: Remove a Users
[3] User: Remove All & Remove Shield
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface"
common_number

case $typed in
    1 ) shield_add_user && shield_user_interface && exit ;;
    2 ) shield_remove_user && shield_user_interface && exit ;;
    #3 ) shield_remove_all && shield_user_interface && exit ;;
    z ) shield_setup && exit ;;
    Z ) shield_setup && exit ;;
    * ) shield_user_interface && exit ;;
esac
}

# Users Management - Add Users #################################################
shield_add_user () {
common_header "🚀  Adding User - Type Exact GMail Address to Add or [Z] to Exit!"
common_number

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then shield_user_interface && exit; fi
if [[ "$typed" == "" ]]; then shield_add_user && exit; fi
if [[ $(echo $typed | grep '@') == "" ]]; then shield_add_user && exit; fi
if [[ $(cat /pg/var/shield/user.list | grep "\<$typed\>") ]]; then
  common_header "WARNING: User Already Exists! Exiting!"
  common_confirm && shield_user_interface && exit; fi
shield_email_add="$typed"
common_header "$shield_email_add - Is this Correct? [Y/N]"
common_number
if [[ "$typed" != "y" || "$typed" != "Y" ]]; then shield_add_user && exit; fi
if [[ $(cat /pg/var/shield/user.list) == "" ]]; then echo $shield_email_add > /pg/var/shield/user.list
else echo $shield_email_add >> /pg/var/shield/user.list; fi
common_header "🚀  $shield_email_add - User Added"
common_confirm
shield_user_interface && exit
}

# Users Management - Remove a User #############################################
shield_remove_user () {

user_wrap=$(fmt -w 79 "/pg/var/shield/user.list")

common_message "🚀  Shield Remove User" "💬 Type Exact Address of User to Remove!

$user_wrap
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface"
common_number

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then shield_user_interface && exit; fi
if [[ "$typed" == "" ]]; then shield_add_remove_user && exit; fi
if [[ $(echo $typed | grep '@') == "" ]]; then shield_remove_user && exit; fi
if [[ $(cat /pg/var/shield/user.list | grep "\<$typed\>") == "" ]]; then
  common_header "WARNING: User Does Not Exist! Resetting"
  common_confirm && shield_remove_user && exit; fi
shield_email_remove="$typed"
common_header "$shield_email_remove - Is this Correct? [Y/N]"
common_number
if [[ "$typed" != "y" || "$typed" != "Y" ]]; then shield_remove_user && exit; fi
common_header "🚀  $shield_email_add - Removed User"
common_confirm
shield_user_interface && exit
}

# Deploy Shield ################################################################
shield_deploy() {
 a=a
}

# Main Interface Execution #####################################################
oauth_traefik=$(docker ps | grep "traefik" )
#if [[ "$oauth_traefik" == "" ]]; then
#common_header "Cannot Configure Until Traefik is Deployed!"
#common_confirm; apps_menu; fi

common_message "🚀  Shield Setup Interface" "💬 More Info? Visit ~ https://plexguide.com/wiki/shield

[1] Web Client        [$shield_wc_display]
[2] Web Secret        [$shield_ws_display]
[3] Authorize Users   [$shield_uc]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[D] Deploy Shield     [NOT-DEPLOYED]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface"
common_number

case $typed in
    1 ) shield_web_client ;;
    2 ) shield_web_secret ;;
    3 ) shield_user_interface ;;
    d ) shield_deploy ;;
    D ) sheild_deploy ;;
    z ) apps_menu ;;
    Z ) apps_menu ;;
    * ) shield_setup ;;
esac

}
