#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
shield_setup() {

shield_setup_start

# WebClient ID Entry ###########################################################
shield_web_client() {
temp_path="/pg/var/shield/web.client"
priorentry=$(cat $temp_path)

common_message "🚀 PlexGuide | Shield: WebClient-ID Interface" "
💾 WebClient-ID for Shield? Visit ~ https://console.developers.google.com

Prior Info Saved (If Any): $priorentry
[Z] To Cancel and Go Back
"

read -p "↘️  New WebClient-ID? | Press [ENTER]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then shield_setup && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && shield_web_client && exit; fi

echo $typed > $temp_path
common_message "💾  $typed - WebClient Set!"
common_confirm && shield_setup && exit
}

# Main Interface Execution #####################################################
oauth_traefik=$(docker ps | grep "traefik" )
#if [[ "$oauth_traefik" == "" ]]; then
#common_header "Cannot Configure Until Traefik is Deployed!"
#common_confirm; apps_menu; fi

common_message "🚀  Shield Setup Interface" "💬 More Info? Visit ~ https://plexguide.com/wiki/shield

[1] Web Client        [$shield_wc]
[2] Web Secret        [$shield_ws]
[3] Authorize Users   [$shield_uc]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[D] Deploy Shield     [NOT-DEPLOYED]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface"
common_number

case $typed in
    z ) apps_menu ;;
    Z ) apps_menu ;;
    * ) shield_setup ;;
esac

}
