#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
start_servername() {

bash /pg/mods/start/quotes.sh
quote=$(cat /pg/var/startup.quote)
source=$(cat /pg/var/startup.source)

}
