#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
start_menu() {

# Need for Tally
drives_menu_start_setup

# Call Variables
edition=$(cat /pg/var/pg.edition)
pgnumber=$(cat /pg/var/pg.number)

common_main /pg/var/server.id NOT-SET serverid
common_main /pg/var/drives/storage.method READ-ONLY storage_method

tee <<-EOF

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🌎 EDITION: $storage_method | Version: PGX Alpha Build | ID: $serverid
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🌵 Used Space: $used of $capacity | $percentage Capacity | Daily Upload: ${tally_total} GB
EOF

  # Displays Second Drive If GCE
  edition=$(cat /pg/var/pg.server.deploy)
  if [ "$edition" == "feeder" ]; then
    used_gce=$(df -h /mnt | tail -n +2 | awk '{print $3}')
    capacity_gce=$(df -h /mnt | tail -n +2 | awk '{print $2}')
    percentage_gce=$(df -h /mnt | tail -n +2 | awk '{print $5}')
    echo "   GCE Disk Used Space: $used_gce of $capacity_gce | $percentage_gce Used Capacity"
  fi

  disktwo=$(cat "/pg/var/hd.path")
  if [ "$edition" != "feeder" ]; then
    used_gce2=$(df -h "$disktwo" | tail -n +2 | awk '{print $3}')
    capacity_gce2=$(df -h "$disktwo" | tail -n +2 | awk '{print $2}')
    percentage_gce2=$(df -h "$disktwo" | tail -n +2 | awk '{print $5}')

    if [[ "$disktwo" != "/pg/unity" ]]; then
    echo "   2nd Disk Used Space: $used_gce2 of $capacity_gce2 | $percentage_gce2 Used Capacity"; fi
  fi

  # Declare Ports State
  ports=$(cat /pg/var/server.ports)

  if [ "$ports" == "" ]; then ports="[OPEN] Ports  "
else ports="[CLOSED] Ports"; fi

if [[ -e "/pg/var/drives/file.stuck" ]]; then file_warning="
WARNING: GDrive 403 ~ https://plexguide.com/wiki/gdrive-403/
"; fi

start_quotes

tee <<-EOF
$file_warning
[1]  Traefik: Reverse Proxy      |  [6]  Press: Word Press Deployment
[2]  Ports  : $ports     |  [7]  Vault: Backup & Restore
[3]  Shield : Google Protection  |  [8]  Cloud: Deploy GCE & Hetzner
[4]  Drives : Data Mounts        |  [9]  Tools: Misc Products
[5]  Apps   : Docker Programs    |  [10] Settings
[Z]  Exit
$main_quote
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EOF
  # Standby
read -p '↘️  Type Number | Press [ENTER]: ' typed < /dev/tty

case $typed in
    1 ) traefik_menu_start && start_menu && exit ;;
    2 ) portguard_menu && start_menu && exit ;;
    3 ) pgshield_menu && start_menu && exit ;;
    4 ) drives_menu_start && start_menu && exit ;;
    5 ) apps_menu && start_menu && exit ;;
    6 ) pgpress_menu && start_menu && exit ;;
    7 ) pgpress_menu && start_menu && exit ;;
    8 ) pgpress_menu && start_menu && exit ;;
    9 ) pgpress_menu && start_menu && exit ;;
    10 ) pgpress_menu && start_menu && exit ;;
    11 ) rm -rf /pg/var/transport/* && echo && drives_uploader && exit ;;
    z ) start_end && exit ;;
    Z ) start_end && exit ;;
    * ) start_menu ;;
esac

}
