#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
traefik_deploy() {

traefik_menu_start_setup
ls -p "$traefik_path/$provider" | grep -v / > "$traefik_path"/provider.keys

traefik_info
ansible-playbook /pg/data/traefik.yml

traefik_postdeploy

}
