#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
traefik_domaincheck() {

digip=$(dig $domain | grep $domain | grep -E -o "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)")
digcheck=$(echo $(ifconfig | grep $digip))

if [[ "$digcheck" == "" && "$provider" != "cloudflare" ]]; then digmessage="
⛔️ WARNING ~ Domain Check Failing - IPV4 'A' correct?"; else digmessage=""; fi

}
