#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
traefik_domain() {

traefik_menu_start_setup

common_message "🚀 PlexGuide | Traefik Domain Interface" "
💾 Domain Utilized for Traefik?

Prior Info Saved (If Any): $domain
[Z] To Cancel and Go Back
"

read -p "↘️  New Domain? | Press [ENTER]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then traefik_menu_start && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && traefik_domain && exit; fi

echo $typed > "$traefik_path/t.domain"

common_message "💾  $typed - New Set Domain!"
common_confirm && traefik_menu_start && exit

}
