#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
traefik_delay() {

traefik_menu_start_setup

common_message "🚀 PlexGuide | Traefik Delay Interface" "
💾 Delay Time Utilized for Traefik?

NOTE: Enables a certain amount of time to be delayed before the provider
validates your Traefik container! Setting it too low may result
in the provider being unable to validate your traefik container, which may
result in MISSING the opportunity to validate your https:// certificates!

Delay Traefik DNS Check for how many seconds? Longer is Better! (Default 75)

Prior Delayed Seconds: $delaycheck
[Z] To Cancel and Go Back
"

read -p "↘️  New Delay? | Press [ENTER]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then traefik_menu_start && exit; fi
if [[ "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && traefik_delay && exit; fi
if [[ "$typed" -lt "10" || "$typed" -gt "180" ]]; then common_message "⛔️  WARNING: Delay must be between 50 to 180 seconds!" && common_confirm && traefik_delay && exit; fi

echo $typed > "$traefik_path"/delay.check

common_message "💾  $typed - New Set Delay Seconds!"
common_confirm && traefik_menu_start && exit

}
