#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
traefik_keys() {

ls -p "$traefik_path/$provider" | grep -v / > /pg/tmp/provider.key.select
focusedkey=$(sed -n "$menutmp"p /pg/tmp/provider.key.select)
if [[ "" -eq "$priorinfo" ]]; then priorinfo="None"; fi

pkey=$(cat "$traefik_path/$provider/$focusedkey")
common_message "🚀 PlexGuide | Traefik Variable Interface" "
💾 What is the input for - $focusedkey?

Prior Info Saved (If Any): $pkey
[Z] To Cancel and GoBack"

read -p "↘️  Set Info - $focusedkey | Press [Enter]: " typed < /dev/tty

if [[ "$typed" == "Z" || "$typed" == "z" ]]; then traefik_menu_start && exit; fi
if [[  "$typed" == "" ]]; then common_message "⛔️  WARNING: Cannot Be Blank" && common_confirm && traefik_keys && exit; fi

echo $typed > "$traefik_path/$provider/$focusedkey"

common_message "💾  $typed saved for $provider - $focusedkey"
common_confirm && traefik_menu_start && exit

}
