#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
traktarr_setup() {

traktarr_vars() {
  common_main /pg/var/traktarr/sonarr.min.year 1960 sonarr_year
  common_main /pg/var/traktarr/radarr.min.year 1960 radarr_year
  common_main /pg/var/traktarr/sonarr.path "" abc
  common_main /pg/var/traktarr/radarr.path "" cde
}

sonarr_year() {
common_header "Set a Minimum Year for Sonarr to Seek!"
common_number
  if [[ "$typed" == "" || "$typed" -le "1899" || "$typed" -ge "2021" ]]; then sonarr_year; fi
echo "$typed" > /pg/var/traktarr/sonarr.min.year
}

radarr_year() {
common_header "Set a Minimum Year for Radarr to Seek!"
common_number
  if [[ "$typed" == "" || "$typed" -le "1899" || "$typed" -ge "2021" ]]; then radarr_year; fi
echo "$typed" > /pg/var/traktarr/radarr.min.year
}

path_check() {
common_message "🚀  Set a Valid Path" "💬 More Info? Visit ~ http://plexguide.com/wiki/traktarr

Set a Valid Path! It should mirror $1's Paths! Type exactly starting with
the / in path, as shown below! Setting the wrong path will overload $1
with the incorrect paths!

EXAMPLES:
/pg/unity/tv     /pg/unity/movies
/local/hd/tv     /local/hd/movies
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface"
common_number
touch $typed/pg.test
if [[ "$typed" == "Z" ||  "$typed" == "z" ]]; then traktarr_setup && exit; fi
if [[ -e "$typed/pg.test" ]]; then
  if [[ "$1" == "Sonarr" ]]; then echo $typed > /pg/var/traktarr/sonarr.path; fi
  if [[ "$1" == "Radarr" ]]; then echo $typed > /pg/var/traktarr/radarr.path; fi
  rm -rf $typed/pg.test
  common_header "💬 $typed is VALID for $1"
  common_confirm
else
  common_header "⛔️ WARNING! Path is Invalid! Try Again!"
  common_confirm
  path_check $1
fi
}

traktarr_vars
if [[ ! -e "/pg/var/token/plex.token" ]]; then touch /pg/var/token/plex.token; fi
if [[ $(cat "/pg/var/token/plex.token") == "" ]]; then plex_token; fi

common_message "🚀  Traktarr PG Interface" "💬 More Info? Visit ~ http://plexguide.com/wiki/traktarr

[1] Trakt API-Key
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[2] Sonarr Path  - NOT SET       [3]  Sonarr Quality  - OUTPUT
[5] Minimum Year - $sonarr_year          [6]  Minimum RunTime - 15 Minutes
[A] Sonarr Options (NOT READY)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[7] Radarr Path  - NOT SET       [8]  Radarr Quality  - OUTPUT
[9] Minimum Year - $radarr_year         [10]  Minimum RunTime - 15 Minutes
[B] Radarr Options (NOT READY)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
[Z] Exit Interface"
common_number

case $typed in
    2 ) path_check Sonarr && traktarr_setup && exit ;;
    7 ) path_check Radarr && traktarr_setup && exit ;;
    5 ) sonarr_year && traktarr_setup && exit ;;
    9 ) radarr_year && traktarr_setup && exit ;;
    z ) start_menu && exit ;;
    Z ) start_menu && exit ;;
    * ) traktarr_setup && exit ;;
esac
}
