---
- name: install {{package_names | join(' ')}} with default package manager
  action: "{{backcompat_pkg_mgr}} name={{item}}"
  register: result_default
  until: result_default is success
  # Workaround https://github.com/ansible/ansible/issues/16868 and
  # increase default retry count
  retries: 20
  delay: 10
  when: >
    should_run and
    package_names is defined and
    package_names and
    (backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt")
  with_items: "{{ package_names }}"
  become: yes

# Handle dnf case for Fedora
- name: "check if {{package_names | join(' ')}} exists"
  command: "rpm -q {{package_names | join(' ')}}"
  changed_when: False
  ignore_errors: True
  register: package_exists_result
  when: >
    should_run and
    package_names is defined and
    package_names and
    backcompat_pkg_mgr == "dnf"
  become: yes

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install {{package_names | join (' ')}} with dnf
  command: dnf install -y {{package_names | join(' ')}}
  register: result_dnf
  until: result_dnf is success
  # Workaround https://github.com/ansible/ansible/issues/16868 and
  # increase default retry count
  retries: 20
  delay: 10
  when: >
    should_run and
    package_names is defined and
    package_names and
    backcompat_pkg_mgr == "dnf" and
    package_exists_result is failed
  become: yes
