- name: Creating download paths
  file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
  with_items:
    - '{{path.stdout}}/downloads/{{pgrole}}'

- name: Creating incomplete paths
  file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
  with_items:
    - '{{path.stdout}}/incomplete/{{pgrole}}'
