#!/bin/bash
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Flicker-Rate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################

# kill double instances before starting
if [[ $(ps -ef | grep 'superstatus.sh' | grep -v "grep" | grep -v "vim" ) ]]; then
	ps -ef | grep 'superstatus.sh' | grep -v "grep" | grep -v "vim" | awk '{print $2}' | xargs kill -9
fi
bash /opt/plexguide/scripts/docker-no/superstatus/superstatus.sh
exit 0
