#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- name: create plexguide network
  docker_network:
    name: "plexguide"
    state: present

- name: "{{role_name}} Container"
  docker_container:
    name: "{{role_name}}"
    state: absent

- name: Create {{role_name}} directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - /opt/appdata/{{role_name}}

- name: Deploy {{role_name}} Container
  docker_container:
    name: "{{role_name}}"
    image: "{{role_name}}/{{role_name}}"
    pull: yes
    cpu_shares: 128
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
     - "/opt/appdata/{{role_name}}:/data"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/opt/appdata/{{role_name}}:/data"
    networks:
      - name: plexguide
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started
### {{role_name}} cannot use auth label; pointless anyways due to creating own user/passwd
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{role_name}}.{{domain.stdout}}"
      traefik.port: "{{intport}}"

- include_role:
    name: pgmend
