#!/bin/bash

    clear
    rm -r /mnt/gdrive/Backup/nginx 1>/dev/null 2>&1
    echo "1. Compressing & Zipping Your Backup Request for NGINX"
    mkdir -p /mnt/gdrive/Backup/nginx
    zip -r /tmp/nginx.zip /opt/appdata/nginx-proxy
    echo "2. Copy Files to Your Google Drive"
    rclone copy /tmp/nginx.zip gdrive:/Backup/nginx -v --checksum --drive-chunk-size=64M 1>/dev/null 2>&1
    rm /tmp/nginx.zip
    echo ""
    echo "Finished - Check Your Google Drive for the Backup Incase!"
    echo ""

read -n 1 -s -r -p "Press any key to continue "
