#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install GCrypt Service
      template:
        src: /opt/plexguide/menu/pgclone/templates/gcrypt.service
        dest: /etc/systemd/system/gcrypt.service
        force: yes

    - name: Start GCrypt SERVICE
      systemd: state=started name=gcrypt daemon_reload=yes enabled=yes
