#!/bin/bash
#
# [Ansible Role]
#
# GitHub:     https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Maintainer: Admin9705 & Deiteq
# URL:        https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
[[ $(pwd) =~ plexguide ]] && cd ~
# If PlexGuide is Missing, it will redownload it
file="/opt/plexguide/menus/"
if [ -e "$file" ]
then
   clear 1>/dev/null 2>&1
else
	dialog --title "Emergency Mode" --msgbox "\nFor some reason, PLEXGUIDE is missing! Your DATA is not lost.  We are downloading the DEVELOPER Version to Help You!" 0 0
	clear
  rm -r /opt/plexguide 1>/dev/null 2>&1
	sudo git clone https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server.git --branch Version-6 /opt/plexguide && sudo bash /opt/plexguide/script/install.sh && clear && echo "Execute PlexGuide Anytime By Typing: plexguide" && echo ""
	exit 0
fi
bash /opt/plexguide/roles/baseline/scripts/gen.sh 1>/dev/null 2>&1

file="/usr/bin/dialog"
if [ -e "$file" ]
then
   clear 1>/dev/null 2>&1
else
   clear
   echo "Installing Dialog"
   apt-get install dialog 1>/dev/null 2>&1
   export NCURSES_NO_UTF8_ACS=1
   echo "export NCURSES_NO_UTF8_ACS=1" >> /etc/bash.bashrc.local
fi

[[ $(pwd) =~ plexguide ]] && cd ~
set -e
sudo rm -r /opt/plexguide

sudo git clone https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server.git --branch Version-6 /opt/plexguide

sudo bash /opt/plexguide/roles/ending/ending.sh
echo "Updated to the latest PlexGuide Dev Version!"
bash /opt/plexguide/roles/baseline/scripts/gen.sh &>/dev/null &
