#!/bin/bash
#
# [Ansible Role]
#
# GitHub:     https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Maintainer: Admin9705 & Deiteq
# URL:        https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
rm -r /opt/plexguide2 1>/dev/null 2>&1
ansible-playbook /opt/plexguide/pg.yml --tags pgedge
rm -r /opt/plexguide 1>/dev/null 2>&1
mv /opt/plexguide2 /opt/plexguide
touch /var/plexguide/ask.yes 1>/dev/null 2>&1
echo "INFO - Selected: Upgrade to PG EDGE" > /var/plexguide/pg.log && bash /opt/plexguide/scripts/log.sh
echo ""
read -n 1 -s -r -p "Press any key to continue"
bash /opt/plexguide/roles/ending/ending.sh
exit
