#!/bin/bash
#
# [Ansible Role]
#
# GitHub:     https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Maintainer: Admin9705 & Deiteq
# URL:        https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
rm -r /var/plexguide/fork.lock 1>/dev/null 2>&1
rm -r /opt/plexguide2 1>/dev/null 2>&1
ansible-playbook /opt/plexguide/pg.yml --tags pgfork

file="/var/plexguide/fork.lock"
if [ -e "$file" ]
then
  rm -r /opt/plexguide 1>/dev/null 2>&1
  mv /opt/plexguide2 /opt/plexguide
fi

bash /opt/plexguide/roles/baseline/scripts/gen.sh &>/dev/null &
