#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
plex_autoscan () {

# VARIABLES ####################################################################
pgrole="plex_autoscan"

common_fcreate_silent /pg/var/plex_autoscan
common_copy /pg/mods/plex_autoscan/* /pg/var/plex_autoscan

traktarr_vars
################################################################################

# JSON EXPORT ##################################################################
cat <<- EOF > "/pg/var/plex_autoscan/config.json"
{
  "core": {
    "debug": false
  },
  "notifications": {
    "verbose": false
  },
  "automatic": {
    "movies": {
      "anticipated": 3,
      "boxoffice": 10,
      "interval": 24,
      "popular": 3,
      "trending": 2
    },
    "shows": {
      "anticipated": 10,
      "interval": 48,
      "popular": 1,
      "trending": 2
    }
  },
  "filters": {
    "movies": {
      "disabled_for": [],
      "allowed_countries": [
        "us",
        "gb",
        "ca"
      ],
      "allowed_languages": [
        "en"
      ],
      "blacklisted_genres": [
        "documentary",
        "music",
        "short",
        "sporting-event",
        "film-noir",
        "fan-film"
      ],
      "blacklisted_min_runtime": ${radarr_time},
      "blacklisted_max_runtime": 0,
      "blacklisted_min_year": ${radarr_year},
      "blacklisted_max_year": 2020,
      "blacklisted_title_keywords": [
        "untitled",
        "barbie",
        "ufc"
      ],
      "rotten_tomatoes": 80
    },
    "shows": {
      "disabled_for": [],
      "allowed_countries": [
        "us",
        "gb",
        "ca"
      ],
      "allowed_languages": [],
      "blacklisted_genres": [
        "news",
        "documentary",
        "special-interest"
      ],
      "blacklisted_networks": [
        "twitch",
        "youtube",
        "espn",
        "fox sports",
        "yahoo!"
      ],
      "blacklisted_min_runtime": ${sonarr_time},
      "blacklisted_max_runtime": 0,
      "blacklisted_min_year": ${sonarr_year},
      "blacklisted_max_year": 2021,
      "blacklisted_title_keywords": []
    }
  },
  "radarr": {
    "api_key": "${radarr_api}",
    "quality": "${sonarr_profile}",
    "minimum_availability": "released",
    "url": "http://0.0.0.0:7878",
    "root_folder": "${path_radarr}"
  },
  "sonarr": {
    "api_key": "${sonarr_api}",
    "language": "English",
    "quality": "${sonarr_profile}",
    "url": "http://0.0.0.0:8989",
    "root_folder": "${path_sonarr}",
    "tags": {}
  },
  "omdb": {
    "api_key": ""
  },
  "trakt": {
    "client_id": "${trakt_client_id}",
    "client_secret": "${trakt_secret_id}"
  }
}
EOF

plex_autoscan_execute() {

plex_autoscan_vars
ansible-playbook /pg/apps/plex_autoscan.yml

# After Actions ################################################################
service_path="/etc/systemd/system/plex_autoscan.service"

if [[ -e "$service_path" ]]; then
common_header "💾  NOTICE:  Stopping/Disabling OLD PAS Service"; sleep 1
systemctl daemon-reload && systemctl stop plex_autoscan && systemctl disable plex_autoscan && rm -rf "$service_path"; fi

cp -f /pg/var/plex_autoscan/plex_autoscan.service "$service_path"
common_header "💾  NOTICE:  Enabling/Starting NEW PAS Service" && sleep 1
systemctl daemon-reload && systemctl enable plex_autoscan && systemctl restart plex_autoscan

common_header "💾  ENABLED: PAS Service"
common_confirm
}

}
