#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
shield () {

container_reset

shield_secret=$(openssl rand -hex 16)
# VARIABLES ####################################################################
pgrole="shield"
image="thomseddon/traefik-forward-auth"
port_inside01="4181"
port_outside01="4181"
traefik_extport="4181"

container_path /etc/localtime /etc/localtime:ro

container_permissions PUID 1000
container_permissions PGID 1000

container_oddball CLIENT_ID ///var
container_oddball CLIENT_SECRET ///var
container_oddball SECRET ${shield_secret}
container_oddball COOKIE_DOMAIN ///var
container_oddball INSECURE_COOKIE True
container_oddball LIFETIME 2592000
container_oddball AUTH_HOST oauth.///domain
container_oddball WHITELIST ///var/whitelist

# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
        env:
          $container_permissions
        labels:
          traefik.enable: 'true'
          traefik.port: '${traefik_extport}'
          traefik.backend: 'oauth'
          traefik.frontend.rule: 'Host:oauth.{$domain--fix}'
          traefik.frontend.auth.forward.address: 'http://oauth:4181'
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

EOF
}
