#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
traktarr () {

# VARIABLES ####################################################################
pgrole="traktarr"

common_fcreate_silent /pg/var/traktarr
common_copy /pg/mods/traktarr/* /pg/var/traktarr

# API KEY EXTRACT FOR SONARR AND RADARR ########################################
if [[ -e /pg/data/radarr/config.xml ]]; then
cat /pg/data/radarr/config.xml config.xml | grep ApiKey | cut -c 11- | rev | cut -c 10- | rev > /pg/var/traktarr/radarr.api;
else echo "" /pg/var/traktarr/radarr.api; fi

if [[ -e /pg/data/sonarr/config.xml ]]; then
cat /pg/data/sonarr/config.xml config.xml | grep ApiKey | cut -c 11- | rev | cut -c 10- | rev > /pg/var/traktarr/sonarr.api;
else echo "" /pg/var/traktarr/sonarr.api; fi
  
# YML EXPORT ###################################################################
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

    - name: Install pip requirements
      pip:
        requirements: /pg/var/traktarr/requirements.txt
        executable: pip3

    - name: Set as Executable
      file:
        path: /pg/var/traktarr/traktarr.py
        owner: '1000'
        group: '1000'
        mode: a+x

    - name: "Create SymLink"
      file:
        src: "/pg/var/traktarr/traktarr.py"
        dest: "/bin/traktarr"
        state: link

####### ALIGN WITH THE A ############################## CORE ###################

### ALIGN WITH THE A ################################## END - EXTRAS ###########

EOF
}

traktarr_execute() {

# After Actions ################################################################
service_path="/etc/systemd/system/traktarr.service"

if [[ -e "$service_path" ]]; then
common_header "💾  NOTICE:  Stopping/Disabling OLD Traktarr Service"; sleep 1
systemctl daemon-reload && systemctl stop traktarr && systemctl disable traktarr && rm -rf "$service_path"; fi

cp -f /pg/var/traktarr/traktarr.service "$service_path"
common_header "💾  NOTICE:  Enabling/Starting NEW Traktarr Service" && sleep 1
systemctl daemon-reload && systemctl enable traktarr && systemctl restart traktarr

common_header "💾  ENABLED: Traktarr Service"
common_confirm
}
