#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
heimdall () {

container_reset                  # do not delete this
# VARIABLES ####################################################################
pgrole="heimdall"
image="linuxserver/heimdall"
port_inside01="443"
port_outside01="1111"
traefik_intport="1111"

# PATHS ########################################################################
# 1st - path on your server # 2nd - path of the container
container_path /pg /pg
container_path /pg/data/$pgrole /config/$pgrole
container_path /pg/data/$pgrole/logs /var/log/logarrlogs
container_path /etc/localtime /etc/localtime:ro

# PERMISSIONS ##################################################################
# pay attention, to exactly what's required for permissions
container_permissions PUID 1000
container_permissions PGID 1000

# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '$portstatus$port_outside01:$port_inside01'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

### END OF FILE ################################################################
EOF
}
