#!/bin/bash
############# https://github.com/plexguide/PlexGuide.com/graphs/contributors ###
plex_auto_scan () {

container_reset
# VARIABLES ####################################################################
pgrole="plex_autoscan "
port_inside01="3468"
port_outside01="3468"
traefik_extport="3468"

container_path /pg /pg
container_path /pg/unity /pg/unity
container_path /pg/data/$pgrole /config
container_path /etc/localtime /etc/localtime:ro

container_permissions PUID 1000
container_permissions PGID 1000

container_docker_user
# IMAGES EXPORT - 1ST IS DEFAULT ###############################################
cat <<- EOF > "/pg/images/$pgrole.images"
sabrsorensen/alpine-plex_autoscan
mrdoob/pascan:latest
mrdoob/pascan:deverlop
EOF

# JSON EXPORT ##################################################################
cat <<- EOF > "/pg/var/plex_autoscan/config.json"
{
   "DOCKER_NAME":"plex",
   "GOOGLE": {
     "ENABLED": false,
     "CLIENT_ID": "${pas_client_id}",
     "CLIENT_SECRET": "${pas_client_secret}",,
     "ALLOWED": {
       "FILE_PATHS": [
         "My Drive/Media/Movies/",
         "My Drive/Media/TV/",
         "My Drive/Media/Music/"
       ],
       "FILE_EXTENSIONS": true,
       "FILE_EXTENSIONS_LIST": [
         "webm","mkv","flv","vob","ogv","ogg","drc","gif",
         "gifv","mng","avi","mov","qt","wmv","yuv","rm",
         "rmvb","asf","amv","mp4","m4p","m4v","mpg","mp2",
         "mpeg","mpe","mpv","m2v","m4v","svi","3gp","3g2",
         "mxf","roq","nsv","f4v","f4p","f4a","f4b","mp3",
         "flac","ts"
       ],
       "MIME_TYPES": true,
       "MIME_TYPES_LIST": [
         "video"
       ]
     },
     "TEAMDRIVE": false,
     "TEAMDRIVES": [],
     "POLL_INTERVAL": 120,
     "SHOW_CACHE_LOGS": false
   },
   "PLEX_ANALYZE_DIRECTORY": true,
   "PLEX_ANALYZE_TYPE": "basic",
   "PLEX_FIX_MISMATCHED": false,
   "PLEX_FIX_MISMATCHED_LANG": "en",
   "PLEX_DATABASE_PATH": "/plexDb/com.plexapp.plugins.library.db",
   "PLEX_EMPTY_TRASH": true,
   "PLEX_EMPTY_TRASH_CONTROL_FILES":[
      "/pg/unity/mounted.bin"
   ],
   "PLEX_EMPTY_TRASH_MAX_FILES": 50,
   "PLEX_EMPTY_TRASH_ZERO_DELETED": true,
   "PLEX_LD_LIBRARY_PATH": "/usr/lib/plexmediaserver/lib",
   "PLEX_LOCAL_URL": "http://plex:32400",
   "PLEX_SCANNER": "/usr/lib/plexmediaserver/Plex\\ Media\\ Scanner",
   "PLEX_SUPPORT_DIR": "/config/Library/Application\\ Support",
   "PLEX_USER": "{$plex_docker_user}",
   "PLEX_TOKEN": "{$pas_token}",,
   "PLEX_CHECK_BEFORE_SCAN": true,
   "PLEX_WAIT_FOR_EXTERNAL_SCANNERS": false,
   "RCLONE": {
    "BINARY": "/usr/bin/rclone",
    "CONFIG": "/home/user/.config/rclone/rclone.conf",
    "CRYPT_MAPPINGS": {
    },
    "RC_CACHE_REFRESH": {
      "ENABLED": false,
      "FILE_EXISTS_TO_REMOTE_MAPPINGS": {
      "Media/": [
          "/mnt/rclone/Media/"
      ]
      },
      "RC_URL": "http://localhost:5572"
    }
  },
   "RUN_COMMAND_BEFORE_SCAN":"",
   "RUN_COMMAND_AFTER_SCAN": "",
   "SERVER_ALLOW_MANUAL_SCAN": true,
   "SERVER_FILE_CHECK_DELAY": 15,
   "SERVER_MAX_FILE_CHECKS": 5,
   "SERVER_FILE_EXIST_PATH_MAPPINGS":{
     "/home/user/rclone/": [
       "/data/"
     ]
   },
   "SERVER_IGNORE_LIST":[
      "Thumbs.db"
   ],
   "SERVER_IP": "0.0.0.0",
   "SERVER_PASS": "${pas_server_pass}",
   "SERVER_PATH_MAPPINGS":{
     "/pg/unity/": [
       "/home/user/media/fused/"
     ]
   },
   "SERVER_PORT": 3468,
   "SERVER_SCAN_DELAY": 15,
   "SERVER_SCAN_FOLDER_ON_FILE_EXISTS_EXHAUSTION": true,
   "SERVER_SCAN_PRIORITIES":{
   },
   "SERVER_USE_SQLITE": true,
   "USE_DOCKER": true,
   "USE_SUDO": false
}

EOF

# YML EXPORT ###################################################################
container_core
cat <<- EOF > "/pg/apps/$pgrole.yml"
$container_header
### ALIGN WITH THE A ################################## START - EXTRAS #########

####### ALIGN WITH THE A ############################## CORE ###################
        $container_start
        published_ports:
          - '${portcheck_add}${port_outside01}:${port_inside01}'
        env:
          $container_permissions
        labels:
        $container_traefik
        $container_oddball
        $container_ending

### ALIGN WITH THE A ################################## END - EXTRAS ###########

EOF
}
