#!/bin/bash
# URL:        PlexGuide.com / PGBlitz.com
# GNU:        General Public License v3.0 
################################################################################
clear
rm -rf /pg
wget -nc https://raw.githubusercontent.com/plexguide/PlexGuide.com/mods/install/main.sh -O- | bash
