#!/bin/bash
# URL:        PlexGuide.com / PGBlitz.com
# GNU:        General Public License v3.0
################################################################################
rm -rf /pg
wget -nc https://raw.githubusercontent.com/PGBlitz/PGBlitz.com/alpha/mods/install/main.sh -O- | bash
