#!/bin/bash
############################################################### PlexGuide.com ##
fpath="/pg/mods/functions"
source "$fpath"/install_sudocheck; install_sudocheck
source "$fpath"/common_path_check; common_path_check

mkdir -p /pg/var/ && rm -rf /pg/var/pg.noinstall
bash /pg/mods/install/main.sh
