#!/bin/bash
# URL:        PlexGuide.com / PGBlitz.com
# GNU:        General Public License v3.0
################################################################################
source /pg/mods/functions/common_path_check
common_path_check

rm -rf /pg/var && mkdir -p /pg/var/ &&rm -rf /pg/var/pg.noinstall
bash /pg/mods/install/main.sh
