#!/bin/bash
# URL:        PlexGuide.com / PGBlitz.com
# GNU:        General Public License v3.0
################################################################################
pgcmd="true"
bash /pg/mods/install/main.sh 
