#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & Flicker-Rate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
############################ Replace Variables
- name: Register Domain
  shell: "cat /var/plexguide/server.domain"
  register: domain
  ignore_errors: True

- name: Register Ports
  shell: "cat /var/plexguide/server.ports"
  register: ports
  ignore_errors: True
############################  Replace Variables
- name: Remove Deluge Container
  docker_container:
    name: deluge
    state: absent

################ DEPLOY
- name: Create Deluge Container
  docker_container:
    name: deluge
    image: binhex/arch-deluge
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}8112:8112"
      - "58846:58846"
      - "58946:58946"
    env:
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: plexguide
        aliases:
          - deluge
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:deluge.{{domain.stdout}}"
      traefik.port: "8112"
    volumes:
      - /opt/appdata/deluge:/config
      - /mnt/deluge/temp:/temp
      - /mnt/deluge/downloaded:/downloaded
      - /mnt/deluge/torrent:/torrent
      - /etc/localtime:/etc/localtime:ro
      - /mnt/unionfs/:/unionfs
    restart_policy: always
    state: started

- name: Restart Container
  docker_container:
    name: deluge
    state: started
