#!/bin/bash

## This is to analyse what taking up space on you drives

#apt install ncdu -y

## to run use name and drive or mount point

#ncdu /
#ncdu /mnt
#ncdu /mnt/nzbget
#ncdu /mnt/sab
#ncdu /mnt/move
#ncdu /mnt/unionfs

### variables to call
#ncdu {{mount.user_input}}

clear

while [ 1 ]
do
CHOICE=$(
whiptail --title "NCDU Directory Size Menu" --menu "Make your choice" 17 55 10 \
    "1)" "Entire drive - excluding /mnt"   \
    "2)" "/mnt"  \
    "3)" "Move"  \
    "4)" "UnionFS"  \
    "5)" "NZBGET"  \
    "6)" "SAB"  \
    "7)" "Deluge"  \
    "8)" "RuTorrents"  \
    "9)" "TorrentVPN"  \
    "10)" "Exit  "  3>&2 2>&1 1>&3
)

result=$(whoami)
case $CHOICE in
    "1)")
      clear
      ncdu / --exclude=/mnt
      ;;

    "2)")
        clear
        ncdu /mnt
        ;;

    "3)")
      clear
      ncdu /mnt/move
      ;;

    "4)")
      clear
      ncdu /mnt/unionfs
      ;;

    "5)")
      clear
      ncdu /mnt/nzbget
      ;;

    "6)")
        clear
        ncdu /mnt/sab
        ;;

    "7)")
        clear
        ncdu /mnt/deluge
        ;;

    "8)")
        clear
        ncdu /mnt/rutorrent
        ;;

     "9)")
         clear
         ncdu /mnt/torrentvpn
         ;;

      "10)")
      clear
      exit 0
      ;;
esac
done
exit
