#!/bin/bash

## Stop all services and unmount drives

fusermount -uz /mnt/unionfs
fusermount -uz /mnt/plexdrive
fusermount -uz /mnt/gdrive
fusermount -uz /mnt/.gcrypt
fusermount -uz /mnt/encrypt


 systemctl stop unionfs
 systemctl stop unionfs-encrypt
 systemctl stop plexdrive
 systemctl stop rclone
 systemctl stop rclone-en
 systemctl stop rclone-encrypt
 systemctl stop move-en
 systemctl stop move
 systemctl stop cache
 systemctl stop encache


systemctl disable unionfs 1>/dev/null 2>&1
systemctl disable unionfs-encrypt 1>/dev/null 2>&1
systemctl disable plexdrive 1>/dev/null 2>&1
systemctl disable rclone 1>/dev/null 2>&1
systemctl disable rclone-en 1>/dev/null 2>&1
systemctl disable rclone-encrypt 1>/dev/null 2>&1
systemctl disable move 1>/dev/null 2>&1
systemctl disable move-en 1>/dev/null 2>&1
systemctl disable cache 1>/dev/null 2>&1
systemctl disable encache 1>/dev/null 2>&1

 systemctl daemon-reload

#sudo umount -l /mnt/unionfs
#sudo umount -l /mnt/plexdrive
#sudo umount -l /mnt/gdrive
#sudo umount -l /mnt/.gcrypt
#sudo umount -l /mnt/encrypt
#sudo umount -l /mnt/move


esac
