#!/bin/bash

### Special thanks goes to https://github.com/kspillane for figuring this out!


# an accurate way to calculate the local network
# Use ifconfig to grab the subnet mask of locip
# Then AND it with locip to get the correct network
# Should work regardless of IP or subnet mask
# Should work with VLSM and CIDR
# Grab the subnet mask from ifconfig

subnet_mask=$(ifconfig | grep $locip | awk -F ':' {'print $4'})
# Use bitwise & with ip and mask to calculate network address
IFSold=$IFS
IFS=. read -r i1 i2 i3 i4 <<< $locip
IFS=. read -r m1 m2 m3 m4 <<< $subnet_mask
IFS=$IFSold
lannet=$(printf "%d.%d.%d.%d\n" "$((i1 & m1))" "$((i2 & m2))" "$((i3 & m3))" "$((i4 & m4))")
