#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Register HD Path
      shell: "cat /var/plexguide/server.hd.path"
      register: path

    - name: Register HD Path
      shell: "cat /var/plexguide/data.location"
      register: tarlocation

    - name: "Size Info"
      shell: "cat /var/plexguide/rclone.size"
      register: program_size

    - name: "Pulling Selected Program"
      shell: "cat /tmp/program_var"
      register: program_var

    - name: "Server ID for Backup"
      shell: "cat /var/plexguide/pg.serverid"
      register: server_id

    - name: "Checking if Program is Running"
      shell: "cat /tmp/docker.check"
      register: running

    - debug: msg="{{program_var.stdout}} running? 1 - Yes | 0 - No >>> {{running.stdout}}"

    - name: Stopping Docker Container - {{program_var.stdout}}
      docker_container:
        name: "{{program_var.stdout}}"
        state: stopped
      ignore_errors: True
      when: running.stdout == "1"

    - name: "Backing Up Program to GDrive - {{program_var.stdout}}"
      archive:
        path:
        - "/opt/appdata/{{program_var.stdout}}/*"
        dest: "{{tarlocation.stdout}}/{{program_var.stdout}}.tar"
        format: tar

    ############ BACKUP OTHER - END
    - name: "Restart Docker Container - {{program_var.stdout}}"
      docker_container:
        name: "{{program_var.stdout}}"
        state: started
      ignore_errors: True
      when: running.stdout == "1"

    - name: "Uploading {{program_var.stdout}}.tar to Google Drive - Size: {{program_size.stdout}} MB"
      shell: "rclone --config /opt/appdata/plexguide/rclone.conf move {{tarlocation.stdout}}/{{program_var.stdout}}.tar gdrive:/plexguide/backup/{{server_id.stdout}} -v --checksum --drive-chunk-size=64M"
