{
 "title": "Traefik  Realtime Stats",
 "description": "Visualize Traefik Health Metrics",
 "time": { "from": "2018-04-16T21:57:44.724Z", "to": "2018-04-18T14:02:48.276Z" },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"traefik\"}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_requests_total{protocol=\"http\"})",
     "legendFormat": "{{http}}"
    },
    {
     "expr": "sum(traefik_backend_requests_total{protocol=\"https\"})",
     "legendFormat": "{{https}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum) / sum(traefik_backend_requests_total) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Requests in last 5 minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total[5m]))",
     "legendFormat": "{{requests}}"
    }
   ]
  },
  {
   "title": "Successful Status Code Count (5min)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{protocol=~\"http|https\",code=\"200\"}[5m])",
     "legendFormat": "{{backend}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Bad Status Code Count (5m)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(traefik_backend_requests_total{protocol=~\"http|https\",code!=\"200\"}[5m])",
     "legendFormat": "{{service}} {{method}} {{code}}"
    }
   ]
  }
 ]
}